# -*- coding: utf-8 -*-
"""Grade 8 — Interaction & AI: Robots That Sense and Express. Full tutor content."""

C = {
    "num": "8", "color": "#8b3fc6", "dark": "#5f2b8a", "light": "#f2e8fa", "tint": "#d8b4fe",
    "theme": "Interaction & AI \u2014 Robots That Sense and Express",
    "form": "mBot2 Rover \u00b7 tank + emoji screen", "codemode": "Blocks \u2192 first Python",
    "capstone": "Companion Robot",
    "units": [
        ("The Rebuild", 5, "#8b3fc6"),
        ("Give It a Face", 4, "#a765d6"),
        ("Machine Learning", 4, "#5f2b8a"),
        ("Generative AI", 2, "#c48be3"),
        ("Control & Code", 2, "#a765d6"),
        ("Capstone: Companion Robot", 3, "#f59e0b"),
    ],
}

S = [
{"n":1, "title":"Review & Teardown",
 "goal":"Grade 7 concepts refreshed, and the mBot2 fully disassembled with every part sorted.",
 "teach":[
   "Open with a fast quiz game on Grade 7 (sense\u2013decide\u2013act, the 360\u00b0 rule, calibration, if/forever, the wobble). Use last year\u2019s capstone scoreboard photo as the first slide \u2014 continuity matters, and it re-activates knowledge this year builds on.",
   "Then the teardown \u2014 and teardown is a skill, not destruction. Rule: a part only leaves the robot if it lands in the correct labeled tray (screws by size, plates, motors, electronics). Reverse-reading the assembly guide teaches the same diagram literacy as building. Handle the CyberPi and sensors like eggs; everything gets reused for the tank."],
 "steps":[
   ("10\u2032","Quiz game in teams \u2014 winner picks their cart shelf first."),
   ("25\u2032","Structured teardown into labeled trays; electronics in their own padded tray."),
   ("5\u2032","Tray inspection against the parts list \u2014 missing parts found NOW, not mid-build."),
   ("5\u2032","Journal: which Grade 7 skill do you expect to reuse most this year? (Revisit in Session 20.)")],
 "tips":["Photograph full trays \u2014 the reference when a screw goes missing next week.",
   "Motors keep their cables attached; unplugging at the board end saves connectors."],
 "result":("teardown", {}),
 "success":["Every part in the correct labeled tray, checked against the list",
   "Electronics undamaged and stored padded","Quiz shows the class can restate all five Grade 7 big ideas"]},

{"n":2, "title":"Tank Build I",
 "goal":"Track assemblies and shock absorbers built \u2014 the Rover\u2019s chassis takes shape.",
 "teach":[
   "The Rover add-on turns the wheeled mBot2 into a tracked tank. Tracks are a different locomotion philosophy: instead of four small contact points, a long footprint that grips slopes, gravel and grass. The shock absorbers are real springs \u2014 the same idea as car suspension, protecting electronics from bumps.",
   "Track tension is today\u2019s precision skill: too loose and the track derails on turns; too tight and the motors strain. The test: a track should deflect a few millimeters under a finger press \u2014 make each team physically feel a good track before signing off."],
 "guide":[
   ("Pages","pp. 5\u201324: brackets \u00d72 \u2192 left wheel \u2192 right wheel"),
   ("Screws","brackets+motor: M4\u00d710 \u00d76 + nuts \u00b7 per wheel: M4\u00d730 + M4\u00d722 (w/ bearings) + M2.5\u00d712 (mBot2 box)"),
   ("Tools","hex end + socket wrench \u00b7 screw panels print 1:1 \u2014 compare")],
 "steps":[
   ("5\u2032","Show the finished Rover (photo/video); name the new parts: tracks, hubs, dampers, D shafts."),
   ("32\u2032","Guide pp. 5\u201324: build the two mirrored wheel brackets, then the complete left and right track-wheel modules (motor, hubs, bearings, track, outer hub)."),
   ("5\u2032","Free-spin + tension test on both modules \u2014 teacher or checker-team fingerpress sign-off."),
   ("3\u2032","Trays back in order; journal: why must a driven wheel still spin freely on its bearing?")],
 "tips":["After each hub screw, back the nut 90\u00b0 counter-clockwise (socket wrench) \u2014 the wheel must spin freely or the motors strain.",
   "Track grain direction matters (magnified inset in the guide); both tracks must point the same way.",
   "Left and right modules mirror each other; building two identical ones is THE classic error.",
   "Track links pinch fingers \u2014 demonstrate the safe grip first."],
 "result":("expl", {"variant":"trackmod"}),
 "success":["Both track-wheel modules complete and mirrored correctly",
   "Every hub spins freely after the 90\u00b0 nut back-off","Track tension + grain direction pass the check"]},

{"n":3, "title":"Tank Build II + Test Drive",
 "goal":"The Rover drives \u2014 and students can explain why tanks turn differently from cars.",
 "teach":[
   "Finish the build, then first drive. The turning revelation: a tank has no steering wheels \u2014 it turns by running the tracks at <b>different speeds</b> (skid steering). Left forward + right backward = spin on the spot, something last year\u2019s robot could never do.",
   "Structure the comparison: same turn command, last year\u2019s video vs. the Rover now. Students articulate the trade-off \u2014 tanks turn on a dime and climb, but are slower on smooth floor. Trade-off remains the word of the year."],
 "guide":[
   ("Pages","pp. 25\u201375: chassis \u2192 head \u2192 join \u2192 shells \u2192 grip arms"),
   ("Chassis","pre-assemble 12 collars (M3\u00d76, screw must not enter the hole) \u00b7 metal shocks \u00d74 (plastic = spares)"),
   ("Head","servos \u00d72 (M4\u00d722 \u00d74 + nuts) drive the L1/R1 arms \u00b7 M4\u00d710/22/30 + socket wrench throughout")],
 "steps":[
   ("18\u2032","Guide pp. 25\u201375 fast lane: chassis (collars, shafts, shocks), head + servos, join halves, shells + bands, arms; cables tucked, QC as in Grade 7."),
   ("12\u2032","First drive (on the floor, never tables) + spin-on-the-spot test; compare against the Grade 7 turn video."),
   ("10\u2032","Mini drills: precise 90\u00b0 and 360\u00b0 spins \u2014 recalibrate turning for tracks (it differs!)."),
   ("5\u2032","Journal: two things tracks do better, two things wheels did better.")],
 "code":("blocks",
"when button A pressed\n  set motors  L +40 / R -40 RPM   <- spin in place\n  wait 1 s\n  stop moving"),
 "tips":["The guide CROSSES the motor cables (left \u2192 right port, right \u2192 left); board film off and servo cables routed BEFORE the shells close.",
   "Turn calibration from Grade 7 is now wrong \u2014 tracks slip differently; recalibrate before precision work."],
 "result":("tank_compare", {}),
 "success":["Rover drives and spins on the spot","Turning recalibrated for tracks (90\u00b0 within a few degrees)",
   "Team stated the tracks-vs-wheels trade-off in their own words"]},

{"n":4, "title":"Terrain Lab",
 "goal":"A real dataset: Rover speed and climbing ability measured across surfaces.",
 "teach":[
   "Today is experimental method dressed as play. Two experiments: (1) speed over a fixed 2 m distance on different surfaces \u2014 tile, carpet, doormat, gravel tray if available; (2) maximum climbable slope using a board propped at increasing angles, measured with a phone inclinometer or a printed protractor.",
   "Insist on fair-test discipline: same robot, same battery level, same command, three trials per condition, record all three (not just the best). The table students fill today is the raw material for Session 5\u2019s graphs \u2014 sloppy data now means garbage graphs tomorrow, and that\u2019s a lesson too."],
 "steps":[
   ("8\u2032","Design the fair test together: what stays constant, what varies, how many trials."),
   ("25\u2032","Stations: speed runs on 3+ surfaces; slope board in 5\u00b0 increments until the Rover fails."),
   ("8\u2032","Data check: every cell of every table filled, units written."),
   ("4\u2032","Predictions in the journal: which surface was fastest, and what will the graph look like?")],
 "tips":["Battery level is the silent confounder \u2014 note it beside each trial.",
   "On the slope board, add a soft landing zone; failed climbs slide back fast."],
 "result":("slope", {"angle":40}),
 "success":["Speed table: 3+ surfaces \u00d7 3 trials, all recorded with units",
   "Maximum slope found to the nearest 5\u00b0","Team can name the two variables they kept constant"]},

{"n":5, "title":"Terrain Science",
 "goal":"Data becomes graphs, and graphs become a verdict on the manufacturer\u2019s 40\u00b0 claim.",
 "teach":[
   "Turn yesterday\u2019s tables into bar charts (speed per surface) and find the class\u2019s maximum-slope distribution. The concepts behind the numbers: <b>friction</b> (grippy surfaces slow top speed but enable climbing) and <b>torque</b> (the twisting force that fights gravity on a slope \u2014 more slope needs more torque at less speed).",
   "Then the headline: Makeblock claims the Rover climbs 40\u00b0. Does class data agree? Maybe teams got 35\u00b0, maybe 42\u00b0 \u2014 either way, discuss why lab conditions differ from marketing conditions (surface, battery, track wear). Students just fact-checked a manufacturer with their own data. That habit \u2014 test the claim \u2014 is the takeaway of the whole unit."],
 "steps":[
   ("15\u2032","Draw the bar charts (paper or spreadsheet); one chart per team on the wall."),
   ("10\u2032","Gallery walk: do all teams agree on the fastest surface? Discuss outliers."),
   ("12\u2032","The 40\u00b0 verdict: compare class results to the claim; list reasons for gaps."),
   ("8\u2032","Journal: your verdict sentence \u2014 \u201cOur data (supports / partly supports / contradicts) the claim because\u2026\u201d")],
 "tips":["Outlier teams usually had a low battery or a curled mat \u2014 hunt the confounder together, don\u2019t discard the data silently.",
   "Keep the wall charts up; they reappear in the capstone as evidence of \u201cour robot\u2019s abilities\u201d."],
 "result":("chart", {"caption":"class dataset: fastest on tile, grippiest on carpet \u2014 claim tested"}),
 "success":["Every team produced a labeled bar chart from real data",
   "Class reached a written verdict on the 40\u00b0 claim","Students can link friction and torque to one result each"]},

{"n":6, "title":"Pixel Art Workshop",
 "goal":"Each team designs original expressions, pixel by pixel, on the Rover\u2019s screen.",
 "teach":[
   "The Rover\u2019s identity lives on its screen. mBlock\u2019s emoji editor works like classic pixel art: a 16\u00d716-ish grid, one square at a time. Show how few pixels carry emotion \u2014 two dots and a curve read as a face from across the room. That economy is a design superpower.",
   "The constraint challenge: express \u201cconfused\u201d in the grid. It\u2019s hard \u2014 confusion has no iconic emoji shape \u2014 which forces real design thinking: tilted eyebrows? A spiral eye? A question mark? Teams draft on paper grids first (fast, erasable), then commit the best to the editor and push it to the actual screen. Seeing your pixels glow on hardware never gets old."],
 "steps":[
   ("8\u2032","Pixel-economy demo: build a smiley live, removing pixels until it stops reading as a face."),
   ("12\u2032","Paper drafts: each student sketches \u201cconfused\u201d on printed grids; team picks one."),
   ("20\u2032","Digitize in the emoji editor and display on the Rover; iterate once after seeing it at distance."),
   ("5\u2032","Screen parade: Rovers line up showing their faces; class guesses each emotion.")],
 "tips":["Judge emojis from 2 meters away \u2014 screens read differently at distance.",
   "Save every emoji with a clear name (confused_v2); the capstone will reuse this library."],
 "result":("pixel", {}),
 "success":["\u201cConfused\u201d displayed on the Rover and correctly guessed by another team",
   "At least two original emojis saved to the team library","Paper-draft-first workflow followed"]},

{"n":7, "title":"Animation",
 "goal":"Emojis come alive: multi-frame animations tied to buttons for three mood states.",
 "teach":[
   "Animation = frames + timing, exactly like a flip-book. A blink is three frames (open, half, closed) played fast; a bounce is position shifts. Two principles go a long way: <b>timing</b> (sleepy is slow, excited is fast \u2014 same frames, different feel) and <b>anticipation</b> (a tiny wind-up before a big move reads as alive).",
   "Build three mood states \u2014 happy, sleepy, surprised \u2014 each an animation loop, each bound to a controller/CyberPi button. This is a state machine without the vocabulary yet: the robot is always in exactly one mood, and buttons switch between them. Session 9 names this idea properly."],
 "steps":[
   ("8\u2032","Flip-book demo: three-frame blink live; change the frame delay, feel the mood shift."),
   ("22\u2032","Teams build three mood animations (2\u20134 frames each) from their emoji library."),
   ("10\u2032","Wire each mood to a button; test switching cleanly between moods."),
   ("5\u2032","Mood quiz: teams switch moods on command; class names each one.")],
 "code":("blocks",
"when button A pressed          <- HAPPY\n  forever\n    show emoji  happy_1 , wait 0.3 s\n    show emoji  happy_2 , wait 0.3 s\n\nwhen button B pressed          <- SLEEPY\n  forever\n    show emoji  sleepy_1 , wait 0.8 s\n    show emoji  sleepy_2 , wait 0.8 s"),
 "tips":["Two mood loops running at once = flickering chaos; each button must stop the previous loop first.",
   "Slow timing (0.6\u20130.9 s) reads as calm; under 0.2 s reads as panic \u2014 use it deliberately."],
 "result":("moods", {}),
 "success":["Three distinct mood animations, each on its own button",
   "Switching moods never shows two animations fighting","Class correctly named all three moods from the screen alone"]},

{"n":8, "title":"Reactive Personality I",
 "goal":"The Rover reacts emotionally to the physical world: shake, darkness, sound.",
 "teach":[
   "Now moods stop being button-driven and become <b>sensor</b>-driven \u2014 the robot appears to feel its environment. Three mappings using CyberPi\u2019s built-in sensors: gyroscope detects a shake \u2192 dizzy face; light sensor sees darkness \u2192 sleepy; microphone hears a clap \u2192 startled jump (a quick backward hop sells it).",
   "Thresholds return from Grade 7, but now they tune <i>personality</i>: a low shake threshold makes a skittish robot; a high one makes it stoic. Let teams tune their robot\u2019s temperament on purpose \u2014 \u201cours is jumpy, ours is chill\u201d \u2014 and suddenly parameters have character. That reframing is the bridge to the capstone."],
 "steps":[
   ("8\u2032","Read raw sensor values on screen: tilt/shake numbers, light level, loudness. Find natural ranges."),
   ("22\u2032","Build the three reactions; tune thresholds to taste."),
   ("10\u2032","Personality demo circle: shake, darken (hands over sensor), clap \u2014 robots react in character."),
   ("5\u2032","Journal: your robot\u2019s temperament in one sentence + the thresholds that create it.")],
 "code":("blocks",
"forever\n  if shake strength > 40\n    show emoji  dizzy , play sound  wobble\n  else if light level < 15\n    show emoji  sleepy\n  else if loudness > 70\n    show emoji  shocked\n    move backward 5 cm fast    <- the startle hop\n  else\n    show emoji  neutral"),
 "tips":["Classroom clapping escalates \u2014 agree the demo protocol before coding the microphone.",
   "The final else (neutral face) matters: without it the robot freezes in its last emotion."],
 "result":("react", {}),
 "success":["All three sensor\u2192emotion mappings work reliably",
   "Thresholds tuned deliberately and recorded","Robot returns to neutral when nothing happens"]},

{"n":9, "title":"Reactive Personality II",
 "goal":"A mood variable with decay makes emotions persist \u2014 plus a structured ethics talk.",
 "teach":[
   "Real moods linger. Introduce a <b>mood variable</b> (say \u22125 to +5): a clap adds +3, a shake \u22122, and every few seconds mood drifts one step back toward 0 (decay). The displayed face reads the variable: high = beaming, low = grumpy, middle = neutral. This is a genuine state machine with memory \u2014 the robot\u2019s reaction now depends on its history, not just the current instant.",
   "Then the 15-minute ethics discussion, structured, not a free-for-all: <i>Is the robot feeling anything?</i> Students just built the mechanism, so they know the answer is no \u2014 it\u2019s a variable. But it <i>looks</i> like feeling, and people bond with things that look like feeling (name a Roomba, thank a voice assistant). Introduce the word <b>anthropomorphism</b>. Land on the question that matters for the capstone: is designing a machine that appears to feel honest? When is it useful (companion robots for the elderly) and when is it manipulative? No forced conclusion \u2014 the discussion continues in their 1-page reflection (assessment)."],
 "steps":[
   ("20\u2032","Build the mood variable: events adjust it, a decay loop drifts it to 0, faces read it."),
   ("8\u2032","Cross-team test: interact with another team\u2019s robot; can you read its mood history?"),
   ("15\u2032","Structured ethics discussion (think\u2013pair\u2013share): is it feeling? Does it matter that it isn\u2019t?"),
   ("2\u2032","Journal: one sentence you\u2019ll defend in the ethics reflection.")],
 "code":("blocks",
"set  mood  to 0\n\nwhen loudness > 70:  change mood by +3\nwhen shake  > 40:  change mood by -2\n\nevery 3 s:                      <- decay\n  if mood > 0: change mood by -1\n  if mood < 0: change mood by +1\n\nforever\n  if mood >= 3: show emoji  beaming\n  else if mood <= -3: show emoji  grumpy\n  else: show emoji  neutral"),
 "tips":["Clamp mood to \u00b15 or one clapping frenzy pins it forever.",
   "In the discussion, ban \u201cit\u2019s just dumb\u201d as a full answer \u2014 require a because."],
 "result":("react", {}),
 "success":["Mood persists after the trigger ends and visibly decays back to neutral",
   "Another team correctly inferred recent history from the robot\u2019s face",
   "Every student voiced or wrote one defensible position in the ethics discussion"]},

{"n":10, "title":"Train Your Robot",
 "goal":"A working image classifier, trained by the students, controlling the Rover.",
 "teach":[
   "mBlock\u2019s Machine Learning 2.0 lets students train an image classifier in the browser: define classes (thumbs-up / thumbs-down / flat hand), show the webcam ~20 examples of each, and the model learns to distinguish them. No formulas needed \u2014 but three words become permanent vocabulary: <b>training data</b> (the examples), <b>classes</b> (the categories), <b>confidence</b> (how sure the model is, in %).",
   "Then wire predictions to behavior: thumbs-up \u2192 drive forward; thumbs-down \u2192 back up; flat hand \u2192 stop. The room goes quiet the first time a robot obeys a gesture \u2014 use that moment to ask the grounding question: <i>did anyone program \u201cthumbs-up\u201d rules?</i> No \u2014 the model learned from examples. That\u2019s the difference between programming and training, stated in one sentence."],
 "steps":[
   ("8\u2032","Create the three classes; discuss what varied examples mean (angles, distances, hands)."),
   ("12\u2032","Collect ~20 samples per class per team; watch live confidence as you train."),
   ("18\u2032","Connect predictions to Rover actions; test with the trainer, then with a teammate."),
   ("7\u2032","Vocabulary check: each student uses training data / class / confidence correctly in one sentence.")],
 "code":("blocks",
"forever\n  if recognition result =  thumbs_up\n    and confidence > 80%\n      move forward at 40 RPM\n  else if result =  thumbs_down\n      move backward at 40 RPM\n  else if result =  flat_hand\n      stop moving"),
 "tips":["Webcam + decent lighting per team is the real constraint \u2014 plan stations if short on cameras.",
   "The confidence threshold (>80%) prevents twitchy misfires; let students feel the difference without it."],
 "result":("ml", {}),
 "success":["Model distinguishes all three gestures at high confidence for its trainer",
   "Rover obeys gestures through the confidence-gated code",
   "All three vocabulary words used correctly by every team"]},

{"n":11, "title":"Break the Model",
 "goal":"Students discover \u2014 by sabotage \u2014 that a model is only as good as its data.",
 "teach":[
   "Great engineers break things on purpose. Today\u2019s lab: make your classifier fail, and document exactly how. Four sabotage stations: (1) retrain with only 3 examples per class \u2014 how accurate now? (2) train in bright light, test in dim; (3) train with one person\u2019s hand, test with another\u2019s; (4) add a \u201cnothing\u201d background class \u2014 does it fix false triggers?",
   "Each failure maps to a data-quality rule: <b>more examples help</b> \u2022 <b>test conditions must match training conditions</b> \u2022 <b>data must cover the variety you\u2019ll meet</b> \u2022 <b>models are confidently wrong, not humble</b> (they output a top class even for nonsense \u2014 unless you gave them a nothing-class). These four rules are the entire practical core of data quality, discovered rather than lectured \u2014 and rule 3 is the doorway to Session 13\u2019s bias discussion."],
 "steps":[
   ("5\u2032","Brief: your mission is to break it \u2014 and write down HOW it broke."),
   ("28\u2032","Rotate the four sabotage stations; log accuracy impressions at each."),
   ("8\u2032","Harvest the four rules on the board from the teams\u2019 findings."),
   ("4\u2032","Journal: the rule that surprised you most, with your evidence.")],
 "tips":["Keep a good backup model saved \u2014 sabotage must be reversible for Session 12.",
   "Station 3 (different hands) is the important one; make sure every team hits it."],
 "result":("ml", {}),
 "success":["Team broke the model in at least three distinct ways, each logged",
   "All four data-quality rules reconstructed by the class",
   "Backup good model intact for next session"]},

{"n":12, "title":"Emotion Mirror",
 "goal":"The kit\u2019s flagship project: the Rover mirrors your facial expression on its screen.",
 "teach":[
   "Everything converges: train classes on facial expressions (smile / frown / neutral \u2014 add surprised if strong), and pipe the prediction to the emoji library from Sessions 6\u20137. Smile at the Rover; it smiles back. Technically it\u2019s Session 10\u2019s pipeline with faces instead of hands \u2014 say so explicitly, because recognizing \u201csame pattern, new data\u201d is what transfer of learning literally is.",
   "Faces are harder than hands: lighting, distance and angle matter more, and the Session 11 rules immediately apply (varied examples! matched conditions!). Teams that struggle should diagnose using the four rules before adding data blindly \u2014 the debug discipline meets the data discipline."],
 "steps":[
   ("10\u2032","Train the expression classes; deliberately varied examples (distance, tilt, glasses on/off)."),
   ("20\u2032","Connect to the emoji library; tune the confidence threshold until mirroring feels instant but stable."),
   ("10\u2032","Mirror booth: each teammate tests; note for whom it works best (data for Session 13)."),
   ("5\u2032","Journal: which of the four data rules did you use today, and where?")],
 "code":("blocks",
"forever\n  if face result =  smile  and confidence > 75%\n    show emoji  happy_big\n  else if result =  frown\n    show emoji  sad\n  else\n    show emoji  neutral"),
 "tips":["A model trained on one teammate often fails on another \u2014 don\u2019t fix it yet; that observation IS Session 13.",
   "Neutral as the fallback class prevents emotional flickering."],
 "result":("mirror", {}),
 "success":["Rover mirrors at least smile / frown / neutral for its trainer",
   "Confidence threshold tuned: responsive but not flickering",
   "Per-person accuracy notes recorded for next session"]},

{"n":13, "title":"Mirror Extensions + Bias \u2731",
 "goal":"Expressions trigger movement \u2014 and the class confronts why the model works better for some people.",
 "teach":[
   "Extend the mirror: smile \u2192 happy spin; frown \u2192 robot backs away sadly; surprise \u2192 startle hop. Emotion now drives <i>behavior</i>, which is exactly the capstone\u2019s ML requirement \u2014 today\u2019s build can be lifted straight into it.",
   "Then the conversation the data has been preparing: pool the class\u2019s per-person accuracy notes. The pattern will be there \u2014 models work best for the people they were trained on, and degrade for faces, skin tones, glasses, or lighting they never saw. Name it: <b>bias</b> \u2014 not malice, but missing data. Connect to the real world briefly and concretely: commercial face systems have shown exactly this failure at scale. The fix students already know from Session 11: representative data. Let them apply it \u2014 retrain with everyone, re-measure, and watch the gap shrink. Bias diagnosed, explained, and reduced with their own hands, in one hour."],
 "steps":[
   ("15\u2032","Build expression \u2192 movement reactions on top of the mirror."),
   ("10\u2032","Pool accuracy notes on the board; find the works-best-for-whom pattern."),
   ("12\u2032","Retrain with every teammate\u2019s face; re-test; compare before/after."),
   ("8\u2032","Discussion: where would this failure matter in the real world? (Seeds the ethics reflection.)")],
 "tips":["Buffer session: the movement extension can shrink to one reaction if time is short \u2014 the bias block cannot.",
   "Keep the tone investigative, not accusatory: the model isn\u2019t mean, it\u2019s under-fed."],
 "result":("mirror", {}),
 "success":["At least two expression-triggered movements working",
   "Class identified the accuracy gap and explained it as a data problem",
   "Retrained model measurably narrowed the gap"]},

{"n":14, "title":"AI Emojis",
 "goal":"Students generate Rover expressions with AI prompts \u2014 and learn that wording is engineering.",
 "teach":[
   "mBlock\u2019s Magic Emoji feature generates screen expressions from choices/prompts: emotion, color, style. It\u2019s generative AI in miniature \u2014 and small is perfect for a first controlled experiment: hold the emotion fixed (\u201cexcited\u201d), vary only the style wording across three attempts, and compare outputs side by side.",
   "The findings to surface: the same prompt can give different results (generative AI is not a vending machine); specific prompts beat vague ones (\u201cexcited, wide sparkling eyes, orange, cartoon\u201d vs. \u201chappy\u201d); and word order/emphasis matters. Contrast with Session 10: a <i>classifier</i> answers \u201cwhich class is this?\u201d, a <i>generator</i> creates something new. Two different animals, both called AI."],
 "steps":[
   ("8\u2032","Demo one generation live; run the same prompt twice \u2014 note the outputs differ."),
   ("22\u2032","Controlled experiment: fixed emotion, three style-wordings, outputs saved side by side."),
   ("10\u2032","Gallery: teams show their triptychs; class extracts \u201cwhat made prompts work\u201d rules."),
   ("5\u2032","Journal: your best prompt, verbatim, and why you think it worked.")],
 "tips":["Generation needs connectivity \u2014 verify accounts and network before class.",
   "Require saving ALL outputs, including failures; the comparison is the data."],
 "result":("prompt", {}),
 "success":["Three-output controlled comparison saved and shown",
   "Team articulated two concrete prompt-improvement rules",
   "Students can state the classifier-vs-generator distinction"]},

{"n":15, "title":"Prompt Recipes",
 "goal":"A reusable prompt recipe card per student, and a hybrid AI + hand-edited signature emoji.",
 "teach":[
   "Formalize yesterday\u2019s findings into a personal <b>prompt recipe card</b>: a fill-in template \u2014 [emotion] + [2\u20133 visual details] + [color] + [style] \u2014 with the student\u2019s own tested examples. Writing the recipe forces the generalization; keeping the card makes prompt skill portable to every AI tool they\u2019ll ever meet. That\u2019s the quiet payload of this session.",
   "Then the hybrid workflow, which mirrors real creative AI practice: generate a base with the recipe, then open it in the pixel editor and hand-fix what the AI got wrong (eyes too small, mouth off-center). AI for the draft, human for the finish. The result becomes the team\u2019s <b>signature emoji</b> \u2014 the face of their capstone character."],
 "steps":[
   ("12\u2032","Write and peer-test recipe cards: swap cards, run a stranger\u2019s recipe, compare intent vs. output."),
   ("22\u2032","Hybrid build: generate with the recipe \u2192 hand-edit pixels \u2192 signature emoji on the Rover."),
   ("8\u2032","Signature parade + one-line \u201cdesign statement\u201d per team."),
   ("3\u2032","File the recipe card in the journal \u2014 it\u2019s a graded artifact.")],
 "tips":["Peer-testing recipes is the quality check: a good recipe works in someone else\u2019s hands.",
   "Timebox the pixel-polishing \u2014 perfectionists will happily spend the hour on one eyebrow."],
 "result":("prompt", {}),
 "success":["Recipe card produced and successfully run by another student",
   "Signature emoji = AI base + visible hand edits, displayed on the Rover",
   "Design statement links the emoji to the intended character"]},

{"n":16, "title":"Controller Mastery \u2731",
 "goal":"Full manual control: joysticks drive, buttons trigger character \u2014 tested on an obstacle course.",
 "teach":[
   "The Bluetooth controller (2 joysticks, 15 buttons) turns the Rover into a drivable character. Critical gotcha, stated up front and loudly: the controller does nothing until the robot runs a program that <i>listens</i> for it \u2014 the robot must be programmed first. This confuses every first-timer; teaching it explicitly saves twenty minutes of \u201cit\u2019s broken\u201d.",
   "Mapping is design: left stick = drive (tank-style: stick Y values to each track), buttons = moods, sounds, speed modes (turbo/precise). Have teams write their mapping on a paper \u201ccontroller card\u201d \u2014 pilots do this. Then the driving gauntlet: a cone/box slalom, a narrow gate, a reverse park. Precise manual driving builds the motor intuition that makes autonomous tuning meaningful."],
 "steps":[
   ("5\u2032","The gotcha demo: dead controller \u2192 load listener program \u2192 alive. Never forgotten."),
   ("18\u2032","Build the mapping: sticks drive, buttons for moods/sounds/speed modes — and L1/R1 for the grip arms, matching Makeblock’s official demo program; fill the controller card."),
   ("17\u2032","Obstacle gauntlet time trials: slalom, gate, reverse park \u2014 penalties for touches."),
   ("5\u2032","Journal: your mapping card + which speed mode won the gauntlet and why.")],
 "code":("blocks",
"forever\n  set motor L to (left stick Y) RPM\n  set motor R to (right stick Y) RPM\n\nwhen controller button  \u25b3  pressed\n  show emoji  happy , play sound  yay\n\nwhen controller button  R1  pressed\n  set  speed_mode  to  turbo"),
 "tips":["Buffer session: the gauntlet can shrink to the slalom only.",
   "Two sticks (one per track) is harder but more \u201ctank-real\u201d than one-stick arcade drive \u2014 offer both, let teams choose.",
   "The official example program maps L1/L2/R1/R2 to the grip arms \u2014 a great reference for teams to study."],
 "result":("controller", {}),
 "success":["Controller drives the Rover with the team\u2019s documented mapping",
   "At least four character buttons live (moods / sounds / speed modes)",
   "Gauntlet completed; time and penalties recorded"]},

{"n":17, "title":"Blocks \u2192 Python",
 "goal":"Students read the Python behind their blocks and successfully predict a code change.",
 "teach":[
   "mBlock has a Python view: the blocks students know, as text. Put a familiar program (the loop-square) side by side with its Python and let them decode it: <code>for i in range(4)</code> is repeat-4, indentation is the \u201cinside\u201d of the block, <code>mbot2.straight(30)</code> is move-forward-30. They already know what this program does \u2014 so they\u2019re not learning to program, just learning a new notation for programs they own.",
   "The method is predict-then-run: change one value in the text (30 \u2192 50, range(4) \u2192 range(6)), write down the prediction, run, verify. End with the mini-challenge: hand-write the pentagram (5 sides, 144\u00b0) in Python from memory of the block version. Grade 9 opens exactly here \u2014 this session is its front porch."],
 "steps":[
   ("10\u2032","Side-by-side decoding of the loop-square; class maps each block to its line."),
   ("15\u2032","Predict-then-run: three single-value edits in Python, predictions written first."),
   ("15\u2032","Mini-challenge: pentagram in Python; run it on the Rover."),
   ("5\u2032","Journal: three block\u2192Python translations you\u2019re sure of.")],
 "code":("python",
"import cyberpi\nimport mbot2\n\n# the Session-8 square, as text\nfor i in range(4):\n    mbot2.straight(30)   # cm\n    mbot2.turn(90)       # degrees\n\ncyberpi.audio.play('yay')\n# challenge: make this the pentagram"),
 "tips":["Function names can differ slightly by mBlock version \u2014 have students trust the editor\u2019s autocomplete over any handout.",
   "Indentation errors are the #1 stumble; show one on purpose and read the error message together."],
 "result":("blocks2py", {}),
 "success":["Team correctly predicted all three edits before running",
   "Pentagram runs from hand-written Python",
   "Students can explain what indentation means in Python"]},

{"n":18, "title":"Capstone: Character Design",
 "goal":"A complete character storyboard, approved before any code is written.",
 "teach":[
   "The brief, in full: design a robot <b>character</b> with (a) a name and visual identity built on the signature emoji, (b) at least three sensor-triggered behaviors, (c) one ML-powered interaction, (d) full controller drive mode. Presented at the Personality Fair (Session 20) where real visitors interact and leave feedback.",
   "Design before code \u2014 the Grade 7 planning gate returns, with a character-sheet template: name, one-line personality, emoji set, behavior table (trigger \u2192 reaction \u2192 what it expresses), ML interaction, controller card. The best characters are <i>coherent</i>: a shy robot startles big and approaches slowly; a party robot celebrates everything. Coherence is a rubric line \u2014 say so. Sign-off question at the gate: \u201cwhy does THIS robot react THIS way?\u201d If the answer is character-driven, they\u2019re ready."],
 "steps":[
   ("8\u2032","Brief + rubric + tour the fair format so the audience is real from the start."),
   ("12\u2032","Character sketching: name, personality line, mood board of emojis."),
   ("18\u2032","Fill the behavior table + ML choice + controller card; optional backpack decoration plan."),
   ("7\u2032","Sign-off interviews with the coherence question.")],
 "tips":["Everything on the sheet must already exist in Sessions 6\u201317 \u2014 the capstone assembles, it doesn\u2019t invent.",
   "Steer ML choices to the mirror (S12) or gestures (S10) \u2014 both are proven pipelines."],
 "result":("character", {}),
 "success":["Character sheet complete: identity + 3 behaviors + ML + controls",
   "Every behavior traces to a session where it was built",
   "Sign-off passed on the coherence question"]},

{"n":19, "title":"Capstone: Build \u2731",
 "goal":"The full character runs end-to-end, rehearsed for visitor interaction.",
 "teach":[
   "Implementation sprint, in flowchart order: identity first (emoji set + idle animation \u2014 quick win), then the three sensor behaviors, then the ML interaction, controller mode last. One piece verified at a time; the mood-loop conflicts from Session 7 will resurface here \u2014 the fix is the same (each state cleanly stops the previous one).",
   "Rehearse for strangers: a visitor won\u2019t know to clap twice at 30 cm. Teams write a small \u201cinteraction sign\u201d (\u201cClap! \u2022 Shake gently! \u2022 Smile at me!\u201d) and test their robot with a member of another team playing naive visitor. What confuses a classmate will confuse a fair visitor twice as much."],
 "steps":[
   ("30\u2032","Build in order: identity \u2192 behaviors \u2192 ML \u2192 controller; verify each before the next."),
   ("10\u2032","Naive-visitor test with another team; fix the top confusion found."),
   ("5\u2032","Write the interaction sign + station checklist for the fair (battery! calibration!).")],
 "tips":["Buffer session: the coherence and the three behaviors are the core; ML can fall back to the proven S12 mirror unchanged.",
   "Freeze code at the end of the hour \u2014 fair-morning tinkering is the classic self-destruct."],
 "result":("character", {}),
 "success":["All character-sheet features run in one continuous demo",
   "A naive visitor triggered every behavior using only the sign",
   "Code frozen; fair checklist written"]},

{"n":20, "title":"Personality Fair",
 "goal":"Visitors meet the robots; teams present; feedback is collected and reflected on.",
 "teach":[
   "Run the fair as stations: each team\u2019s Rover on a table with its interaction sign and feedback cards (\u201cWhich emotion did you see? \u2605 rating \u2022 What surprised you?\u201d). Invite an audience if at all possible \u2014 another class, teachers, younger students; robots performing for strangers is a different sport, and students rise to it.",
   "Close with the year\u2019s real question: <i>what made an interaction feel alive?</i> Harvest answers \u2014 usually: it responded fast, it looked at me, it had moods, it remembered (the decay variable!). Note that every answer is a design decision they made. Then the Grade 9 teaser: \u201cnext year, your robot gets an arm and a job.\u201d The ethics reflection (1 page, assessment) goes home with them: anthropomorphism, training data, bias \u2014 they have lived all three."],
 "steps":[
   ("8\u2032","Station setup: robots, signs, feedback cards, fresh batteries."),
   ("25\u2032","The fair: visitors rotate; half of each team hosts while the other half visits, then swap."),
   ("8\u2032","Read feedback cards; each team shares its favorite and its most useful criticism."),
   ("4\u2032","\u201cAlive\u201d harvest + Grade 9 teaser + ethics reflection handed out.")],
 "tips":["Charge everything beforehand; a dead robot at a fair is heartbreak.",
   "Photograph each station \u2014 these images open Grade 9, Session 1."],
 "result":("fair", {}),
 "success":["Every robot was operated successfully by at least three visitors",
   "Feedback cards collected and one improvement named per team",
   "Ethics reflection assigned with lived examples to draw on"]},
]


# --- Revision: exact pieces per the official Rover add-on box packing list (photo-verified)
PARTS = {
 1:[("robot_wheel","last year\u2019s build, to disassemble"),("screwdriver",None),("trays","screws / plates / motors / electronics"),("roverbox","unbox + inventory vs. its parts chart"),("journal",None)],
 2:[("guide","pp. 5\u201324 \u2014 in the Rover box"),("track","\u00d72 \u2014 grain direction!"),("trackhubs","big \u00d74 halves + small \u00d72"),("collarflange","flange bearings \u00d74"),("bracket","T \u00b7 U \u00b7 90\u00b0 \u2014 two mirrored sets"),("motorcable","motors from the mBot2 teardown"),("screwsR","M4\u00d710 \u00d712 \u00b7 M4\u00d730 \u00d72 \u00b7 M4\u00d722 \u00d72 \u00b7 M2.5\u00d712 \u00d72 + nuts"),("socket","nut back-off 90\u00b0 CCW"),("screwdriver",None)],
 3:[("dshaft","\u00d76 + collars \u00d712 (M3\u00d76)"),("damper","METAL \u00d74 \u2014 plastic = spares"),("beamplate","2\u00d74 \u00b7 2\u00d76 \u00b7 T \u00b7 3\u00d78"),("servopack","\u00d72 \u2014 grip arms (M4\u00d722 \u00d74)"),("boards","shells 1\u20138 + bands \u2014 film OFF first"),("cyberpi","+ shield, charged"),("screwsR","M4\u00d710/22/30 + nuts \u00b7 drivers + socket wrench"),("laptop","first tank drive")],
 4:[("robot_tank","QC\u2019d"),("laptop",None),("ramp","board on books"),("protractor","or phone inclinometer"),("ruler","2 m speed course"),("timer","3 trials each"),("journal","data tables")],
 5:[("journal","yesterday\u2019s raw data"),("laptop","or graph paper"),("cards","wall-chart paper"),("robot_tank","re-runs for outliers")],
 6:[("robot_tank",None),("laptop","emoji editor"),("cards","printed 16\u00d716 pixel grids"),("journal","emoji library list")],
 7:[("robot_tank",None),("laptop",None),("journal","frame storyboards")],
 8:[("robot_tank",None),("laptop",None),("journal","threshold notes")],
 9:[("robot_tank",None),("laptop",None),("journal","ethics position sentence")],
 10:[("robot_tank",None),("laptop","ML 2.0 access"),("webcam","1 per team or station"),("journal","vocabulary check")],
 11:[("robot_tank",None),("laptop",None),("webcam",None),("journal","sabotage log")],
 12:[("robot_tank",None),("laptop",None),("webcam","good lighting matters"),("journal","per-person accuracy notes")],
 13:[("robot_tank",None),("laptop",None),("webcam",None),("journal","bias before/after data")],
 14:[("robot_tank",None),("laptop","online \u2014 generation needs the network"),("journal","save ALL outputs")],
 15:[("robot_tank",None),("laptop",None),("cards","recipe-card template"),("journal","recipe card is graded")],
 16:[("robot_tank",None),("laptop","program the listener FIRST"),("controller","in the Rover box"),("dongle","advised \u2014 sold separately"),("boxes","slalom + gate"),("tape","course marks"),("timer","gauntlet times")],
 17:[("robot_tank",None),("laptop","Python view"),("usb","stable connection helps"),("journal","3 translations")],
 18:[("journal","character sheet \u2014 deliverable"),("cards","sheet template + rubric"),("robot_tank","reference only \u2014 no coding today")],
 19:[("robot_tank",None),("laptop",None),("controller",None),("webcam","if ML = mirror"),("cards","interaction sign"),("shield","charge overnight!")],
 20:[("robot_tank","code frozen"),("controller",None),("webcam",None),("cards","visitor feedback cards"),("shield","fully charged"),("tape","station setup")],
}
