# -*- coding: utf-8 -*-
"""Grade 9 — Engineering & Autonomy: Robots That Work. Full tutor content."""

C = {
    "num": "9", "color": "#d97706", "dark": "#9a4f08", "light": "#fdf0dd", "tint": "#fcd34d",
    "theme": "Engineering & Autonomy \u2014 Robots That Work",
    "form": "mBot2 Ranger \u00b7 tank + robotic arm", "codemode": "Full Python",
    "capstone": "Robots at Work",
    "units": [
        ("Python Bootcamp", 4, "#d97706"),
        ("Better Control", 3, "#f0a13c"),
        ("The Arm", 5, "#9a4f08"),
        ("Integration", 2, "#f0a13c"),
        ("Capstone: Robots at Work", 6, "#16a34a"),
    ],
}

PY_NOTE = "Function names below follow mBlock\u2019s CyberPi Python API; minor names vary by version \u2014 the class rule is: trust the editor\u2019s autocomplete."

S = [
{"n":1, "title":"Same Robot, New Language",
 "goal":"Every student writes and runs a Python program that drives a square \u2014 in pairs.",
 "teach":[
   "Open with the Grade 8 fair photos, then the year\u2019s premise: same robot, professional tools. mBlock\u2019s Python mode is a real editor \u2014 text, autocomplete, error messages. The first program is deliberately familiar: the square. They\u2019ve built it in blocks (Grade 7) and read it in Python (Grade 8, Session 17); today they type it from a blank file. Familiar problem + new medium = confidence, not overwhelm.",
   "Institute <b>pair programming</b> as this year\u2019s standard: driver types, navigator reads ahead and catches errors; swap every 10 minutes. It\u2019s how professionals work and it halves the syntax frustration of week one. Also set the error-message culture: an error message is information, not an insult \u2014 read it aloud, bottom line first."],
 "steps":[
   ("8\u2032","Editor tour: file, run, stop, console, autocomplete. Break something on purpose; read the error together."),
   ("20\u2032","Pairs type the square from scratch; run on the robot; swap roles halfway."),
   ("12\u2032","Extension ladder: triangle \u2192 hexagon \u2192 any-N polygon (the 360/N insight, now as code)."),
   ("5\u2032","Journal: one error message you met and what it was telling you.")],
 "code":("python",
"import cyberpi\nimport mbot2\n\n# our old friend, typed from scratch\nfor i in range(4):\n    mbot2.straight(30)    # cm forward\n    mbot2.turn(90)        # degrees right\n\ncyberpi.display.show_label('done!', 24, 'center')"),
 "tips":[PY_NOTE,
   "IndentationError and missing colons will dominate today \u2014 predict it aloud so nobody feels alone.",
   "Pairs stay together for the whole Python Bootcamp unit."],
 "result":("pyeditor", {"shape":"square","caption":"typed Python drives the same square as Grade 7\u2019s blocks",
   "code_lines":["import mbot2","","for i in range(4):","    mbot2.straight(30)","    mbot2.turn(90)"]}),
 "success":["Square runs from hand-typed Python","Pair-programming roles practiced with a swap",
   "At least one error message read, decoded, and fixed by the pair"]},

{"n":2, "title":"Functions",
 "goal":"Motion wrapped into reusable, parameterized functions \u2014 the vocabulary of clean code.",
 "teach":[
   "A function is a named behavior: define <code>square(size)</code> once, call it anywhere, change it in one place. Connect backwards: functions are to code what loops were to repeated blocks in Grade 7 \u2014 the next rung on the same ladder (don\u2019t repeat yourself). The parameter is the power move: <code>square(20)</code>, <code>square(40)</code> \u2014 one definition, infinite squares.",
   "Build a small personal library today: <code>square(size)</code>, <code>polygon(n, size)</code>, <code>celebrate()</code> (LEDs + sound). This library literally gets imported into the capstone \u2014 tell them that now, so \u201cwrite it well\u201d has a reason. Naming matters: <code>celebrate()</code> reads like English; <code>func2()</code> reads like regret."],
 "steps":[
   ("10\u2032","Live-code square() together; call it three times with different sizes."),
   ("15\u2032","Pairs build polygon(n, size) \u2014 the 360/N rule becomes one line of math in code."),
   ("12\u2032","Design celebrate() freely: lights + sound + a wiggle; must be a single call."),
   ("8\u2032","Library review: swap code with another pair; can they use your functions without asking you?")],
 "code":("python",
"import mbot2, cyberpi\n\ndef polygon(n, size):\n    for i in range(n):\n        mbot2.straight(size)\n        mbot2.turn(360 / n)\n\ndef celebrate():\n    cyberpi.led.on(255, 180, 0)\n    cyberpi.audio.play('yay')\n\npolygon(5, 25)   # pentagon, one line\ncelebrate()"),
 "tips":["The another-pair-can-use-it test is the real definition of a good function.",
   "Watch for logic vs. syntax confusion: polygon(3, ...) turning 120\u00b0 is correct \u2014 remind them of the exterior angle."],
 "result":("pyeditor", {"shape":"square","caption":"one function, many shapes \u2014 the personal library begins",
   "code_lines":["def polygon(n, size):","  for i in range(n):","    mbot2.straight(size)","    mbot2.turn(360/n)","","polygon(4, 30)"]}),
 "success":["polygon(n, size) draws at least three different shapes",
   "celebrate() runs as a single call","Another pair used the library without explanations"]},

{"n":3, "title":"Sensing in Python",
 "goal":"Live sensor values read, displayed and logged \u2014 the robot\u2019s senses in text form.",
 "teach":[
   "Sensors in Python return numbers you can hold in a variable: <code>d = cyberpi.ultrasonic2.get()</code>. That one line changes the relationship \u2014 in blocks, values flowed invisibly; in Python, students capture, print, compare and compute with them. Build the classic diagnostic tool first: a loop printing distance to the screen ten times a second (a live dashboard, and their debugging best friend for the rest of the year).",
   "Then the line sensor: it reports how far off-center the line is (an <b>offset</b>, roughly \u2212100\u2026+100). Have students push the robot along a line by hand and watch the number swing negative\u2013zero\u2013positive. That number IS next week\u2019s error signal for P-control; today they just need to feel what it measures."],
 "steps":[
   ("12\u2032","Build the distance dashboard; verify against a ruler; find sensor limits again (they know the drill)."),
   ("12\u2032","Threshold play: print \u2018NEAR!\u2019 when d < 15 \u2014 an if on a captured value."),
   ("15\u2032","Line offset explorer: hand-push the robot along a line, watch the offset swing; sketch its meaning."),
   ("6\u2032","Journal: what does offset = \u221260 mean physically? Draw it.")],
 "code":("python",
"import cyberpi, mbot2, time\n\nwhile True:\n    d = cyberpi.ultrasonic2.get()\n    off = cyberpi.quad_rgb_sensor.get_offset_track()\n    cyberpi.display.show_label('d=' + str(d), 16, 'top')\n    cyberpi.display.show_label('off=' + str(off), 16, 'center')\n    if d < 15:\n        cyberpi.display.show_label('NEAR!', 24, 'bottom')\n    time.sleep(0.1)"),
 "tips":[PY_NOTE,
   "str(d) trips everyone \u2014 numbers must become text to display; let them hit the error, then explain.",
   "Calibrate the line sensor first (the Grade 7 ritual) or the offset numbers are noise."],
 "result":("pyeditor", {"shape":"log","caption":"a live sensor dashboard \u2014 the year\u2019s debugging companion",
   "code_lines":["while True:","  d = ultrasonic2.get()","  show('d=' + str(d))","  if d < 15:","    show('NEAR!')","  time.sleep(0.1)"]}),
 "success":["Dashboard shows live distance + line offset","NEAR! fires at the right threshold",
   "Team can explain offset\u2019s sign and rough magnitude physically"]},

{"n":4, "title":"Logic & Refactor",
 "goal":"Grade 7\u2019s obstacle avoidance rebuilt in Python \u2014 then refactored into a clean function.",
 "teach":[
   "Full control flow: <code>if / elif / else</code> and <code>while</code>. The vehicle is deliberately nostalgic \u2014 rewrite Grade 7\u2019s wander mode in Python. They know exactly what it should do, so all attention goes to expressing it in the new language: a while-True loop, a distance check, the back-up-and-random-turn escape.",
   "Then introduce <b>refactoring</b>: improving code\u2019s shape without changing its behavior. Extract the escape maneuver into <code>avoid()</code>, name the magic numbers as constants (<code>SAFE_CM = 12</code>), and re-run \u2014 identical robot behavior, radically clearer code. That \u201csame behavior, better shape\u201d discipline is the heart of code quality, and it\u2019s a rubric line in the capstone code review."],
 "steps":[
   ("15\u2032","Rewrite wander in Python: while True + distance check + escape."),
   ("15\u2032","Refactor: extract avoid(), name constants, add two comments that say WHY not what."),
   ("10\u2032","Arena test: does refactored wander behave identically? (It must \u2014 that\u2019s the definition.)"),
   ("5\u2032","Journal: before/after code snippets \u2014 which would you rather debug at 11 pm?")],
 "code":("python",
"import mbot2, cyberpi, random\n\nSAFE_CM = 12          # escape trigger distance\nCRUISE  = 40          # RPM\n\ndef avoid():\n    mbot2.straight(-10)\n    mbot2.turn(random.randint(60, 120))\n\nwhile True:\n    if cyberpi.ultrasonic2.get() < SAFE_CM:\n        avoid()\n    else:\n        mbot2.forward(CRUISE)"),
 "tips":["random.randint needs the import \u2014 a good \u2018read the error\u2019 moment.",
   "\u2018Why not what\u2019 comments: # escape trigger distance, not # set SAFE_CM to 12."],
 "result":("wander", {}),
 "success":["Python wander roams the arena reliably","avoid() extracted; constants named; behavior unchanged",
   "Comments explain why, not what"]},

{"n":5, "title":"The Wobble, Explained",
 "goal":"Students understand proportional control conceptually \u2014 correction proportional to error.",
 "teach":[
   "Resurrect Grade 7\u2019s board question: <i>why does the line follower zig-zag?</i> Now they can answer it. Bang-bang control knows only three answers (hard left / straight / hard right) \u2014 it always overcorrects, overshoots, and corrects back: the wobble is built into the logic. The fix is one idea: <b>make the correction proportional to the error</b>. Slightly off \u2192 tiny steering nudge; far off \u2192 strong steering. In code it will be one line: <code>steer = error \u00d7 gain</code>.",
   "Teach it with the blindfold walk before any code: one student walks a taped line blindfolded; their partner may only say \u201cleft\u201d/\u201cright\u201d (bang-bang) \u2014 watch them wobble. Then allow \u201ca little left\u201d / \u201cway left\u201d (proportional) \u2014 the walk visibly smooths. Ten minutes of theatre worth a thousand words. Then define terms on the board: <b>error</b> (the line offset they measured in Session 3), <b>gain</b> (how aggressively we respond), and predict together what too-low gain (drifts off curves) and too-high gain (wobbles again!) will look like tomorrow."],
 "steps":[
   ("12\u2032","Blindfold line-walk, bang-bang vs. proportional instructions; debrief what changed."),
   ("12\u2032","Board the model: error \u2192 \u00d7 gain \u2192 steering; connect error to Session 3\u2019s offset number."),
   ("14\u2032","Paper-trace the algorithm on drawn scenarios: offset \u221260, gain 0.5 \u2192 motors? Teams compute by hand."),
   ("7\u2032","Predictions in the journal: sketch what gain-too-low and gain-too-high trajectories will look like.")],
 "tips":["Do NOT code today \u2014 the concept needs its own hour; tomorrow\u2019s implementation then takes minutes.",
   "The hand computation (offset \u00d7 gain \u2192 two motor speeds) is the comprehension gate; don\u2019t skip it."],
 "result":("graph2", {"caption":"the prediction: proportional control should tame the wobble"}),
 "success":["Class answered the Grade 7 wobble question in control terms",
   "Teams hand-computed motor speeds from offset \u00d7 gain correctly",
   "Both failure predictions (low/high gain) sketched"]},

{"n":6, "title":"P-Control",
 "goal":"Proportional line following implemented and tuned \u2014 the wobble visibly defeated.",
 "teach":[
   "Implementation day: read the offset, multiply by gain, split the result across the two tracks. The core is genuinely three lines \u2014 emphasize that a big idea can be small code. Then tuning: start with a low gain, raise it until the robot hugs curves, and keep going until it wobbles again (yesterday\u2019s prediction comes true \u2014 applaud it, it means the model is right).",
   "Tuning protocol is Session 15/13 discipline: one gain value \u2192 one timed lap \u2192 log it \u2192 change once. Teams produce a small gain table (gain / lap time / observation) and pick their champion value. Vocabulary upgrade: they are tuning a <b>control loop</b> \u2014 the same mathematics that keeps drones level and cruise control steady. They should know the thing they built today is not a toy idea."],
 "steps":[
   ("12\u2032","Type the P-follower; first run at gain \u2248 0.3 \u2014 expect lazy curve-cutting."),
   ("22\u2032","Tuning sprints: gain table with 5+ values, timed laps, one change at a time."),
   ("8\u2032","Champion runs: best gain, three laps, best time recorded next to Grade 7\u2019s bang-bang times."),
   ("3\u2032","Journal: your gain table + the value where wobble returned.")],
 "code":("python",
"import mbot2, cyberpi\n\nBASE = 45      # cruise RPM\nGAIN = 0.5     # tune me!\n\nwhile True:\n    err = cyberpi.quad_rgb_sensor.get_offset_track()\n    steer = err * GAIN            # the whole idea\n    mbot2.drive_speed(BASE + steer, BASE - steer)"),
 "tips":[PY_NOTE,
   "If the robot flees the line instantly, the offset sign is inverted \u2014 flip the +/\u2212 and move on.",
   "Same track and battery across tuning laps, or the table lies."],
 "result":("line", {"wobble":False,"kind":"tank","caption":"P-control: the trajectory finally hugs the line"}),
 "success":["P-follower completes laps visibly smoother than bang-bang",
   "Gain table with 5+ tested values, one-change discipline","Wobble-returns gain found, matching the prediction"]},

{"n":7, "title":"Measure It",
 "goal":"Claims become graphs: error over time proves proportional beats bang-bang.",
 "teach":[
   "Engineers don\u2019t say \u201cit looks smoother\u201d \u2014 they show a graph. Today: log the error signal while driving (append offset values to a list, or print them and transcribe), then plot error-vs-time for bang-bang and for P-control. The bang-bang plot is a square wave bouncing between extremes; the P-control plot shrinks and settles. One picture, whole argument.",
   "Pair it with lap-time data: P-control is usually both smoother AND faster \u2014 a rare free lunch, and worth noticing. Fast teams get the D-term teaser: error \u00d7 gain still overshoots a little because it reacts to where the robot IS, not where it\u2019s HEADING; adding a term based on how fast error is changing (the derivative) damps that. Even implementing nothing, knowing PID exists \u2014 and that they built the P \u2014 is the doorway out of this course into real control engineering."],
 "steps":[
   ("15\u2032","Add error logging to both followers; drive 20 s each, capture the series."),
   ("15\u2032","Plot both series (paper grid or spreadsheet); overlay or side-by-side."),
   ("10\u2032","Compare + write the two-sentence evidence-based conclusion under the graphs."),
   ("5\u2032","D-term teaser for all; extension pairs may prototype it.")],
 "code":("python",
"errors = []\nfor i in range(200):          # ~20 s of driving\n    err = cyberpi.quad_rgb_sensor.get_offset_track()\n    errors.append(err)\n    steer = err * GAIN\n    mbot2.drive_speed(BASE + steer, BASE - steer)\n    time.sleep(0.1)\n\nprint(errors)                 # copy out for plotting"),
 "tips":["Transcribing 200 numbers is misery \u2014 sample every 5th, or screenshot the console.",
   "The conclusion sentence must cite the graph (\u2018peak error fell from ~90 to ~25\u2019), not vibes."],
 "result":("graph2", {}),
 "success":["Both error-time plots produced from real logged data",
   "Written conclusion cites numbers from the graphs",
   "Team can say what the D in PID would add"]},

{"n":8, "title":"Ranger Build I",
 "goal":"Teardown and the Ranger tank base built \u2014 the third and final form begins.",
 "teach":[
   "The Ranger is the kit\u2019s final form: tracked base plus a servo-driven robotic arm. Today: structured teardown of the Rover (the Grade 8 tray ritual \u2014 they know it; hold them to it) and the tank base per the digital guide. Logistics note repeated from the plan: the Ranger guide is <b>digital-only</b> \u2014 have it downloaded, projected, and ideally printed before class; a dead link kills the hour.",
   "Build quality bar is higher this year: the base will carry a moving arm, so torsional rigidity matters \u2014 loose frame screws that were tolerable on the Rover become arm-shake later. The QC checklist gains a line: twist-test the frame gently; nothing should creak or flex visibly."],
 "steps":[
   ("12\u2032","Rover teardown into trays; electronics padded; parts checked against the Ranger list."),
   ("28\u2032","Tank base from the guide: front unit (pp. 5\u201314), then chassis (pp. 15\u201329); frame screws snugged in a cross pattern."),
   ("5\u2032","QC + twist test; label robots; journal: what will the arm demand from this base?")],
 "guide":[
   ("Guide","mBot2 Ranger Quick Start Guide (the digital ZIP, 61 printed pp.): front unit pp. 5\u201314 \u2192 chassis pp. 15\u201329. NOT the help-center\u2019s \u201cmBot Ranger\u201d \u2014 different, older kit"),
   ("Screws","front unit opens \u00d78+\u00d78+\u00d78; same fastener system as the Rover (M4\u00d710/22/30 + nuts, socket wrench); 3 parts reused from the mBot2 box \u2014 read panel counts off the projected guide"),
   ("Watch-outs","wheel screws: tighten, then slightly counter-clockwise so the wheel rotates \u00b7 track grain direction, checked on BOTH sides")],
 "tips":["Download the guide in advance \u2014 digital-only, and school wifi chooses violence on demo days.",
   "Track tension lesson from Grade 8 applies verbatim; fingerpress test again."],
 "result":("build", {"stage":"half"}),
 "success":["Teardown complete, trays verified","Tank base passes QC + twist test",
   "Ranger guide accessible offline for next session"]},

{"n":9, "title":"Ranger Build II",
 "goal":"The arm assembled \u2014 and understood as levers, torque and gear ratios in metal.",
 "teach":[
   "Assemble the arm: servo, linkage, gripper. Then teach the machine they just built. The arm is a <b>lever</b>: the servo twists at the joint, the load hangs at the tip \u2014 the longer the arm, the more <b>torque</b> the same load demands (why cranes are thick at the base and thin at the tip). If the design routes power through gears: the ratio trades speed for force, like bicycle gears \u2014 climbing gear vs. sprint gear.",
   "Make it tactile: unpowered, let students feel the difference between pushing the arm near the joint vs. at the tip. Then the engineering consequence: servos have limits \u2014 stall a servo against an obstacle and it overheats. That physical fact becomes next session\u2019s software rule: safe ranges, enforced in code. Hardware limits \u2192 software constants; that\u2019s embedded engineering in one arrow."],
 "steps":[
   ("25\u2032","Guide pp. 30\u201361: robotic arm (30\u201335), grippers \u00d72 (36\u201343 \u2014 \u201crepeat for the other arm\u201d), finish + cabling (44\u201361); route cables so full arm travel never pulls them taut."),
   ("10\u2032","Feel-the-lever stations: joint vs. tip resistance; find the arm\u2019s natural range by hand, gently."),
   ("7\u2032","Board: lever \u2192 torque \u2192 servo limit \u2192 \u2018safe range in code\u2019 arrow; write the numbers found by hand."),
   ("3\u2032","Journal: label a sketch of the arm with joint, load, and where torque is highest.")],
 "guide":[
   ("Guide","same ZIP: arm pp. 30\u201335 \u2192 grippers pp. 36\u201343 (build TWO) \u2192 finish + cabling pp. 44\u201361; 3 rear D shafts, then \u2018Done!\u2019"),
   ("Screws","gripper \u2192 servo plate: M4\u00d710 \u00d74 + nuts \u00d74 per arm (guide-verified); gripper shells \u00d71+\u00d72 boards + rubber band per arm"),
   ("Cables","STRAIGHT this year: left motor \u2192 EM1, right \u2192 EM2 \u2014 the Rover crossed them, this build does NOT \u00b7 servo cables \u2192 S4 (left) / S3 (right) \u00b7 short plastic ring first, then long")],
 "tips":["Students who remember Grade 8 will \u2018helpfully\u2019 cross the motor cables \u2014 the Ranger wires them STRAIGHT; crossed here means every turn runs backwards.",
   "Never force the arm past resistance \u2014 gear teeth strip silently and are not in the spare bag.",
   "The hand-found range (e.g. \u22480\u00b0 floor to \u2248100\u00b0 up) becomes tomorrow\u2019s constants \u2014 write it down per robot."],
 "result":("arm", {"pose":"lift"}),
 "success":["Arm assembled; full travel without cable tension","Team stated the lever/torque story on their own sketch",
   "Physical safe range measured and recorded per robot"]},

{"n":10, "title":"First Arm Motions",
 "goal":"The arm moves under Python control, with hardware limits enforced as named constants.",
 "teach":[
   "First powered motion: command the arm servo to angles from Python. Start ceremonial \u2014 lift, hold, lower, applause \u2014 then immediately install the engineering discipline: yesterday\u2019s hand-measured range becomes <code>ARM_FLOOR</code> and <code>ARM_TOP</code> constants, and every arm command goes through a guard function <code>arm_to(angle)</code> that clamps requests into the safe range. The robot should be physically unable to hurt itself through code.",
   "This is the session\u2019s big idea, bigger than the arm: <b>defensive programming</b> \u2014 code that assumes mistakes will happen and contains them. Test it adversarially: call <code>arm_to(500)</code> on purpose; the guard should quietly deliver ARM_TOP. Fast pairs add speed control (move in small steps with sleeps) and discover smooth vs. jerky motion \u2014 aesthetics through timing, an echo of Grade 8\u2019s animation lesson."],
 "steps":[
   ("12\u2032","First powered lift/lower; find the servo command in autocomplete; map angle \u2192 physical position."),
   ("18\u2032","Build arm_to() with clamping; constants from yesterday\u2019s measurements; adversarial tests."),
   ("10\u2032","Choreography mini-challenge: a 3-pose salute using only arm_to() calls."),
   ("5\u2032","Journal: why should limits live in ONE place (the guard) rather than at every call site?")],
 "code":("python",
"import mbot2, time\n\nARM_FLOOR = 0      # measured by hand, Session 9\nARM_TOP   = 100\n\ndef arm_to(angle):\n    # defensive: clamp into the safe range\n    angle = max(ARM_FLOOR, min(ARM_TOP, angle))\n    mbot2.servo_set(angle, 1)   # servo port 1\n\narm_to(80)   # lift\ntime.sleep(1)\narm_to(500)  # attack the guard -> goes to 100\narm_to(10)   # lower"),
 "tips":[PY_NOTE + " The servo call especially varies \u2014 find it together in autocomplete.",
   "If the arm judders at range edges, back the constants off 5\u00b0 \u2014 mechanical margins are wisdom."],
 "result":("arm", {"pose":"lift"}),
 "success":["Arm moves to commanded angles via arm_to() only",
   "Guard proven by adversarial calls","3-pose salute runs smoothly"]},

{"n":11, "title":"Pick & Place",
 "goal":"The gripper earns its keep: lift a block, carry it, stack two \u2014 a challenge ladder.",
 "teach":[
   "The challenge-ladder format: rungs of increasing difficulty, teams climb at their own pace, each rung demoed to the teacher before the next. Rung 1: grip and lift a foam block (grip force/angle tuning \u2014 too loose drops, too tight bends). Rung 2: lift, drive 30 cm, set down inside a taped zone (arm + motion coordination, and the discovery that driving shakes the payload \u2014 slower is surer). Rung 3: stack a second block on the first (precision: approach angle, release height \u2014 drop from too high and the tower falls).",
   "Let the struggle happen \u2014 rung 3 is genuinely hard and that\u2019s its job. The debug discipline carries: one variable per attempt (grip angle OR approach speed OR release height), logged. Teams should end today knowing their gripper\u2019s personality: what it holds well, where it fumbles. That self-knowledge writes Session 12\u2019s failure log."],
 "steps":[
   ("8\u2032","Ladder briefing + demo protocol; blocks and zones distributed."),
   ("32\u2032","Climb: grip\u2192lift (R1), carry\u2192place (R2), stack (R3); teacher demos at each rung."),
   ("5\u2032","Standings + journal: your highest rung and the single change that unlocked it.")],
 "tips":["Foam blocks only \u2014 wooden ones strip servo gears on a bad grip.",
   "R2 zone generous (A5-size) today; precision tightens in the capstone."],
 "result":("arm", {"pose":"stack"}),
 "success":["Rung 2 (carry & place) reached by every team",
   "Rung 3 attempted with logged one-change attempts","Gripper strengths/weaknesses written down"]},

{"n":12, "title":"Reusable Arm Code",
 "goal":"pick(), place(), goto() \u2014 the arm\u2019s verbs, plus an honest failure log.",
 "teach":[
   "Yesterday\u2019s working sequences become a library: <code>pick()</code> (open, lower, close, lift), <code>place()</code> (lower, open, retreat, lift), <code>goto_cm(d)</code> (drive helper). The capstone mission will then read like English: <code>follow_line() \u2026 pick() \u2026 goto_cm(30) \u2026 place()</code>. When top-level code reads like the mission description, the decomposition is right \u2014 that\u2019s the design smell to teach.",
   "Second deliverable: the <b>failure log</b>. Run pick() twenty times; count successes; describe every failure precisely (\u2018block rotated in grip when arm passed 60\u00b0\u2019, not \u2018it dropped it\u2019). An 85% gripper is fine \u2014 an <i>unknown</i>-% gripper is a time bomb in a scored mission. Reliability engineering in one lunch-sized lesson: measure it, then decide whether to fix it or design around it (e.g. re-grip attempt on failure \u2014 which is Session 19\u2019s recovery topic, seeded today)."],
 "steps":[
   ("18\u2032","Extract pick(), place(), goto_cm() from yesterday\u2019s code; parameters where useful."),
   ("15\u2032","Failure log: 20 pick() runs, success count + precise failure notes."),
   ("8\u2032","Library swap-test (the Session 2 ritual): another pair runs your pick() cold."),
   ("4\u2032","Journal: your reliability %, and fix-it vs. design-around-it \u2014 which will you choose?")],
 "code":("python",
"def pick():\n    grip_open()\n    arm_to(ARM_FLOOR + 5)\n    grip_close()\n    time.sleep(0.3)      # let the grip settle\n    arm_to(60)           # carry height\n\ndef place():\n    arm_to(ARM_FLOOR + 10)\n    grip_open()\n    mbot2.straight(-5)   # retreat before lifting\n    arm_to(60)"),
 "tips":["The sleep after grip_close matters \u2014 servos need a beat; its absence is the ghost bug of the week.",
   "Failure descriptions must name conditions; \u2018sometimes\u2019 is banned vocabulary."],
 "result":("journal", {"caption":"the failure log \u2014 reliability measured, not assumed",
   "items":["pick() runs: 20","success: 17  (85%)","fail: rotates past 60\u00b0","fail: edge grip on tilt","plan: slow lift 60\u201380\u00b0"]}),
 "success":["pick()/place()/goto_cm() pass the swap-test",
   "20-run failure log with precise descriptions","A reliability decision made and written down"]},

{"n":13, "title":"Navigate + Manipulate \u2731",
 "goal":"The full pipeline in miniature: follow line \u2192 detect marker \u2192 stop \u2192 pick \u2192 deliver.",
 "teach":[
   "Integration day \u2014 the capstone in miniature, and deliberately so: line following (Session 6) + color-marker detection (Grade 7, Session 16\u2019s idea, now in Python) + arm library (Session 12) chained into one mission. The new engineering content is the <i>seams</i>: stopping accurately AT the marker (momentum overshoots \u2014 the two-speed approach returns yet again), and positioning the arm relative to a block whose location is only as precise as the stop was. Errors compound down a pipeline; students meet that truth physically today.",
   "Run it as a milestone session: the pipeline working once, even slowly and inelegantly, is the win. Teams that get a clean run should immediately answer the harder question: how repeatable? Three runs in a row is the real bar \u2014 and the gap between \u2018worked once\u2019 and \u2018works reliably\u2019 is the theme of the entire build-sprint unit ahead."],
 "steps":[
   ("8\u2032","Whiteboard the pipeline; identify the two seams (stop accuracy, arm alignment)."),
   ("30\u2032","Build and iterate; markers and blocks on the standard course; one-change discipline at the seams."),
   ("7\u2032","Milestone attempts: pipeline end-to-end; then repeatability count (n clean of 3).")],
 "code":("python",
"while True:\n    err = cyberpi.quad_rgb_sensor.get_offset_track()\n    if cyberpi.quad_rgb_sensor.is_color('green'):\n        mbot2.EM_stop()\n        break\n    steer = err * GAIN\n    mbot2.drive_speed(BASE + steer, BASE - steer)\n\npick()\nmbot2.turn(180)\ngoto_cm(40)\nplace()\ncelebrate()      # Session 2, still earning its keep"),
 "tips":["Buffer session \u2014 a struggling class can pre-place the block at a fixed, known stop point.",
   "Slow the BASE speed near expected markers; detection at speed is flaky and that\u2019s a real sensor lesson."],
 "result":("work", {}),
 "success":["Full pipeline ran end-to-end at least once","Both seams named with their observed failure mode",
   "Repeatability measured (n of 3), whatever the n"]},

{"n":14, "title":"Program Structure",
 "goal":"The mission code restructured around a main loop + state variable \u2014 and paper-traced first.",
 "teach":[
   "Session 13\u2019s pipeline was a straight script \u2014 fine until something fails mid-mission and the program can\u2019t express \u2018go back and retry\u2019. Introduce the <b>state machine</b> pattern: a state variable (SEARCHING / APPROACHING / PICKING / DELIVERING / DONE), a main loop that reads sensors and, depending on the current state, acts and decides transitions. It\u2019s Grade 8\u2019s mood variable wearing a hard hat \u2014 say exactly that; the recognition lands.",
   "Before running: <b>paper trace</b>. One teammate is the CPU: finger on the current state, walk through a scenario (\u2018marker seen \u2192 state becomes PICKING\u2019), including the nasty ones (\u2018what if the grip fails in PICKING?\u2019 \u2192 they\u2019ll want a retry transition \u2014 let them invent it). Tracing catches design holes in minutes that debugging would find in hours; it is also precisely how they\u2019ll explain their code in the capstone review."],
 "steps":[
   ("12\u2032","Board the state diagram for the S13 mission; agree states and transitions as a class."),
   ("10\u2032","Paper trace in pairs, including two failure scenarios; patch the diagram where it breaks."),
   ("18\u2032","Restructure the code to the state pattern; behavior should match S13\u2019s (refactor discipline!)."),
   ("5\u2032","Journal: your state diagram, photographed or redrawn.")],
 "code":("python",
"state = 'SEARCHING'\n\nwhile state != 'DONE':\n    if state == 'SEARCHING':\n        follow_line_step()\n        if see_marker():\n            state = 'PICKING'\n    elif state == 'PICKING':\n        if pick_ok():\n            state = 'DELIVERING'\n        else:\n            state = 'SEARCHING'   # retry path!\n    elif state == 'DELIVERING':\n        goto_cm(40); place()\n        state = 'DONE'"),
 "tips":["States are NOUNS-in-progress, transitions are events \u2014 keep the diagram honest.",
   "If the trace can\u2019t answer \u2018what happens if X\u2019, the code can\u2019t either; fix the diagram first."],
 "result":("pyeditor", {"shape":"log","caption":"the mission as a state machine \u2014 retry paths included",
   "code_lines":["state = 'SEARCHING'","while state != 'DONE':","  if state=='SEARCHING':","    ...","  elif state=='PICKING':","    ...retry on fail..."]}),
 "success":["State diagram covers the mission incl. one retry path",
   "Paper trace survived two failure scenarios","Restructured code matches S13 behavior"]},

{"n":15, "title":"Design Sprint",
 "goal":"Each team\u2019s capstone mission fully specified, scoped and signed off.",
 "teach":[
   "The brief, in full: design an autonomous mission simulating a real job \u2014 warehouse sorting, rescue supply delivery, harvesting, waste collection, or the team\u2019s own pitch. The robot must navigate (line or programmed path), detect a target (marker/color), manipulate (pick and deliver at least one object) \u2014 fully autonomously. Demo Day (Session 20): scored runs plus a 5-minute pitch that must include one honest failure story.",
   "Today produces four artifacts, in order: <b>problem statement</b> (what real job, why it matters \u2014 the pitch\u2019s backbone); <b>success criteria</b> (measurable: \u2018delivers 2 blocks to zones in <90 s, 2 of 3 runs\u2019); <b>course sketch</b> (top-down, dimensions, line path, marker and zone positions); <b>task breakdown</b> mapped onto Sessions 1\u201314 (every task should point at a session where its skill was built \u2014 anything pointing nowhere is scope risk, cut it or flag it). The sign-off gate is strictest of all three years: ambition is celebrated, unscoped ambition is returned for revision. \u2018Impressive and finished\u2019 beats \u2018amazing and imaginary\u2019 \u2014 write it on the board."],
 "steps":[
   ("8\u2032","Brief + rubric + example missions pitched fast (steal-able starting points)."),
   ("12\u2032","Problem statement + success criteria drafted; criteria must contain numbers."),
   ("18\u2032","Course sketch + task breakdown with session references."),
   ("7\u2032","Sign-off interviews: scope probe (\u2018which task is riskiest? what\u2019s your cut line?\u2019).")],
 "tips":["Ban criteria without numbers \u2014 \u2018works well\u2019 is not a criterion.",
   "Require a written cut line: the feature they\u2019ll drop first if time runs short. Deciding it now removes the mid-sprint agony."],
 "result":("journal", {"caption":"the signed mission spec \u2014 numbers, sketch, cut line",
   "items":["job: pharmacy delivery","succeed: 2 zones < 90 s","course: fig. 8 + 2 markers","riskiest: double pick","cut line: 2nd delivery"]}),
 "success":["All four artifacts complete; criteria numeric","Every task maps to a source session",
   "Cut line written; sign-off passed"]},

{"n":16, "title":"Build Sprint I \u2731",
 "goal":"Navigation milestone: the robot completes its course path end-to-end, reliably.",
 "teach":[
   "Sprint rules, borrowed from real teams: a 2-minute standup at the top (each team: done / doing / blocked \u2014 blockers get teacher attention first), then heads-down build, then a milestone check at the end. Today\u2019s milestone for everyone regardless of mission: <b>navigation end-to-end</b> \u2014 the robot travels its full course path and stops where the mission needs it, three times in a row.",
   "Hold the line on order: teams itching to build the arm show first that the robot can reliably <i>arrive</i>. Navigation is the foundation every later behavior stands on; a wobbly foundation makes every arm bug ambiguous (\u2018did the grip fail or did we stop 4 cm short?\u2019). Reliability before features \u2014 it\u2019s the sprint\u2019s only commandment."],
 "steps":[
   ("5\u2032","Standup circle: done / doing / blocked; blockers triaged."),
   ("33\u2032","Build: course laid out to the sketch\u2019s dimensions; navigation tuned on the real course."),
   ("7\u2032","Milestone check: 3 consecutive end-to-end navigation runs, witnessed and logged.")],
 "tips":["Buffer session: teams behind on P-control tuning catch up here \u2014 that IS their navigation work.",
   "Courses on the floor get shuffled between sessions; photograph the layout with a tape measure in frame."],
 "result":("kanban", {}),
 "success":["3 consecutive clean navigation runs on the team\u2019s own course",
   "Standup done in under 2 minutes with a real blocked-list","Course layout photographed for exact rebuild"]},

{"n":17, "title":"Build Sprint II + Code Review",
 "goal":"Manipulation development advances \u2014 and every team\u2019s code survives a peer review.",
 "teach":[
   "Build continues (arm behaviors onto the navigation spine), but the hour\u2019s signature event is the <b>cross-team code review</b> \u2014 the professional practice, scaled down. Pairs of teams swap laptops and read each other\u2019s code against a four-line checklist: <i>functions with clear names? \u00b7 constants instead of magic numbers? \u00b7 comments that say why? \u00b7 no copy-pasted near-duplicates?</i> Reviewers write two \u2018strengths\u2019 and two \u2018suggestions\u2019 \u2014 the discipline of kind precision.",
   "Frame it before anyone reads a line: review is about the code, not the coder; every suggestion is a gift that saves a future debugging hour. The checklist is the capstone rubric\u2019s code-quality section verbatim \u2014 so today is a free mock exam. Teams then get sprint time to act on what review found; acting on feedback is the half of the skill that classrooms usually skip."],
 "steps":[
   ("5\u2032","Standup + review protocol and the four-line checklist."),
   ("12\u2032","Cross-team review: read, checklist, write 2 strengths + 2 suggestions."),
   ("23\u2032","Sprint: apply at least one review suggestion, then continue manipulation build."),
   ("5\u2032","Milestone pulse: where is each team vs. the plan? Cut lines re-checked aloud.")],
 "tips":["Model one review comment style first: \u2018pick() is very readable\u2019 / \u2018GAIN=0.5 appears 3\u00d7 \u2014 constant?\u2019",
   "A team \u2018too busy to review\u2019 is the team that most needs it \u2014 the checklist takes 12 minutes, hold firm."],
 "result":("kanban", {}),
 "success":["Review exchanged: 2+2 written comments per team",
   "At least one suggestion applied the same hour","Manipulation visibly progressed on the mission course"]},

{"n":18, "title":"Build Sprint III",
 "goal":"Full mission integration: navigation + manipulation attempts on the complete course.",
 "teach":[
   "Integration week peaks: manipulation joins navigation and full mission attempts begin. Expect the seam bugs from Session 13 at mission scale \u2014 stop accuracy vs. arm alignment \u2014 plus the new one: <b>cumulative drift</b> over a longer course (small navigation errors sum; missions that pick early and deliver late feel it most). The state-machine structure from Session 14 earns its keep now: teams with clean states can add a re-align step to one state without touching the rest.",
   "Keep a visible run log per team on the wall: attempt number, phases completed, failure point. The log turns frustration into data \u2014 \u2018we fail at delivery 3 of 4 times\u2019 is actionable; \u2018it keeps breaking\u2019 is despair. It also quietly writes the failure-story half of the pitch. Teams at their cut line make the cut today, without shame \u2014 point at the board from Session 15."],
 "steps":[
   ("5\u2032","Standup; run-log sheets posted per team."),
   ("33\u2032","Full mission attempts; every attempt logged; fixes between runs follow one-change discipline."),
   ("7\u2032","Milestone: at least one full-mission success, or the cut executed and the reduced mission succeeding.")],
 "tips":["Enforce the log \u2014 memory lies under sprint pressure, paper doesn\u2019t.",
   "Battery sag changes stop distance late in the hour; note battery level in the log too (Grade 7 wisdom, still true)."],
 "result":("work", {}),
 "success":["Full mission completed at least once (original or post-cut scope)",
   "Run log with phase-level failure data","One drift/seam fix implemented via a single state change"]},

{"n":19, "title":"Rehearsal & Pitch Prep \u2731",
 "goal":"Failure recovery hardened, run configuration frozen, and the 5-minute pitch rehearsed.",
 "teach":[
   "Two workstreams. <b>Robot</b>: rehearse under Demo-Day conditions (official start, audience noise simulated, two attempts) and add cheap recovery where the run log points \u2014 the classics: re-grip once if pick fails (Session 12\u2019s seed sprouts), re-find line if lost (Grade 7\u2019s search behavior returns), timeout-and-skip rather than freeze forever. Then freeze the configuration \u2014 the Grade 7 race-config ritual, now second nature.",
   "<b>Pitch</b> (5 minutes, strict): the problem (30 s) \u2192 the solution & how it works (2\u2032) \u2192 live demo (90 s) \u2192 <b>one honest failure story</b> and what it taught (1\u2032). The failure story is mandatory and rubric-weighted \u2014 it\u2019s where engineering maturity shows, and after three years of debug discipline every team has a good one. Rehearse with a timer; cutting to fit five minutes is itself the exercise. Assign demo roles: driver (starts the run), narrator (talks over it), catcher (handles the robot if chaos wins)."],
 "steps":[
   ("18\u2032","Recovery pass: implement the top recovery the run log justifies; verify it triggers correctly."),
   ("8\u2032","Freeze: race configuration written, code committed, no edits after this line."),
   ("15\u2032","Pitch rehearsal \u00d72 with timer; peers give one keep / one cut note."),
   ("4\u2032","Demo-day logistics: order drawn, roles assigned, batteries on chargers.")],
 "tips":["Buffer session: recovery can shrink to timeout-and-skip only \u2014 but the freeze and the timed rehearsal are untouchable.",
   "The failure story must end on the lesson, not the excuse \u2014 coach the last sentence."],
 "result":("demo", {}),
 "success":["One recovery behavior demonstrably triggers and works",
   "Configuration frozen in writing","Pitch fits 5:00 with all four parts, twice"]},

{"n":20, "title":"Demo Day",
 "goal":"Scored autonomous runs, real pitches, and a three-year retrospective that lands.",
 "teach":[
   "Run it as the event three years earned: audience seated (invite classes, teachers, parents if possible), visible scoreboard (phase points per team\u2019s own success criteria + small style bonus), two attempts each with pit time between, pitches delivered from the front. The teacher\u2019s job today is master of ceremonies \u2014 the students carry the content, and they can.",
   "Close the arc deliberately. The retrospective ritual: the Session 1/Grade 7 question projected (\u2018what is a robot?\u2019) \u2014 let them answer it again, now with three years of hands. Then the pathways talk, concrete and short: what they built maps to real fields \u2014 control engineering (their P-controller), ML engineering (their mirror), embedded software (their guard functions), robotics competitions, and the kit\u2019s 30+ module ecosystem for a robotics club afterlife. End on the honest sentence: they didn\u2019t learn about robotics \u2014 they did robotics, sixty hours of it."],
 "steps":[
   ("8\u2032","Setup: courses rebuilt from photos, scoreboard up, order posted, audience seated."),
   ("30\u2032","The event: per team \u2014 pitch (5\u2032 incl. live demo) with scored attempts; pit repairs allowed between rounds."),
   ("5\u2032","Awards: precision, engineering, comeback, audience choice."),
   ("2\u2032","Retrospective question + pathways + the closing sentence.")],
 "tips":["Rebuild courses from the tape-measure photos \u2014 \u2018the course moved\u2019 is a heartbreak with a known cure.",
   "Score against each team\u2019s OWN success criteria \u2014 missions differ; fairness lives in the spec they signed."],
 "result":("demo", {}),
 "success":["Every team: two scored attempts + a complete 5-minute pitch",
   "Failure stories told and applauded","Scoreboard archived; three-year arc closed"]},
]


# --- Revision: exact pieces per the two boxes (photo-verified); arm parts come from the Rover add-on box
PARTS = {
 1:[("robot_tank","from Grade 8"),("laptop","mBlock Python mode"),("journal","error-message notes")],
 2:[("robot_tank",None),("laptop",None),("journal","library design notes")],
 3:[("robot_tank",None),("laptop",None),("map","line for the offset explorer"),("ruler","verify distances"),("journal","offset sketch")],
 4:[("robot_tank",None),("laptop",None),("boxes","arena"),("journal","before/after snippets")],
 5:[("tape","taped line on the floor"),("blindfold","the control-theory theatre"),("journal","hand computations"),("cards","printed offset scenarios")],
 6:[("robot_tank",None),("laptop",None),("map","same track all laps"),("timer","lap times"),("journal","gain table"),("shield","same battery level across laps")],
 7:[("robot_tank",None),("laptop",None),("map",None),("journal","graph paper"),("cards","or spreadsheet")],
 8:[("robot_tank","to tear down"),("trays","the ritual"),("track",None),("trackhubs",None),("dshaft",None),("damper",None),("screwsR","+ socket wrench & screwdriver"),("laptop","Ranger guide \u2014 DOWNLOADED")],
 9:[("servopack","the arm\u2019s muscle"),("bracket",None),("beamplate","arm linkage"),("boards","gripper + mounts"),("rubber","grip traction"),("screwsR","+ both drivers"),("socket",None),("journal","safe-range numbers")],
 10:[("robot_arm","built + range measured"),("laptop",None),("usb",None),("journal","why-one-guard answer")],
 11:[("robot_arm",None),("laptop",None),("foam","NOT wooden blocks"),("tape","placement zones"),("journal","rung log")],
 12:[("robot_arm",None),("laptop",None),("foam",None),("journal","failure log \u2014 20 runs")],
 13:[("robot_arm",None),("laptop",None),("map",None),("patches","the pick marker"),("foam",None),("tape","delivery zone")],
 14:[("robot_arm",None),("laptop",None),("journal","state diagram \u2014 deliverable"),("cards","trace scenarios")],
 15:[("journal","spec: 4 artifacts"),("ruler","course dimensions"),("cards","rubric + example missions"),("robot_arm","feasibility checks only")],
 16:[("robot_arm",None),("laptop",None),("map","or taped path"),("tape","course build"),("foam",None),("timer",None),("phone","photograph the layout + tape measure")],
 17:[("robot_arm",None),("laptop",None),("cards","review checklist \u00d72 per team"),("foam",None),("journal","2+2 review notes")],
 18:[("robot_arm",None),("laptop",None),("foam",None),("journal","run log on the wall"),("shield","log battery level too")],
 19:[("robot_arm",None),("laptop",None),("timer","strict 5:00"),("journal","frozen race config"),("cards","pitch structure card")],
 20:[("robot_arm","frozen config"),("laptop",None),("foam",None),("timer","+ scoreboard"),("shield","charged overnight"),("phone","course rebuild photos"),("cards","award certificates")],
}
