# -*- coding: utf-8 -*-
"""Grade 7 — Foundations: Think Like a Robot. Full tutor content."""

C = {
    "num": "7", "color": "#0e7fc1", "dark": "#0a5c8c", "light": "#e3f1fa", "tint": "#7dd3fc",
    "theme": "Foundations \u2014 Think Like a Robot",
    "form": "mBot2 \u00b7 wheeled base", "codemode": "Block-based coding",
    "capstone": "Rescue Run",
    "units": [
        ("Meet Your Robot", 4, "#0e7fc1"),
        ("Motion & Geometry", 3, "#2a9fd8"),
        ("Loops & Expression", 2, "#55b7e4"),
        ("Sensing: Ultrasonic", 4, "#0a5c8c"),
        ("Line Following", 3, "#2a9fd8"),
        ("Capstone: Rescue Run", 4, "#f59e0b"),
    ],
}

S = [
# ---------------- UNIT 1
{"n":1, "title":"What Is a Robot?",
 "goal":"Students can explain the sense\u2013decide\u2013act loop and apply it to everyday machines.",
 "teach":[
   "A robot is a machine that <b>senses</b> its environment, <b>decides</b> what to do using a program, and <b>acts</b> on the world \u2014 then repeats that loop, often many times per second. A hammer acts but never senses; a thermometer senses but never acts. A robot needs all three.",
   "Run the card sort: give pairs 10\u201312 cards with machines (vacuum robot, drone, calculator, thermostat, hammer, automatic door, washing machine\u2026). Teams sort into \u201crobot\u201d / \u201cnot a robot\u201d and must justify each choice using the three-part test. Disagreements are gold \u2014 a thermostat is a great edge case."],
 "steps":[
   ("8\u2032","Card sort in pairs; teams defend two of their choices to the class."),
   ("7\u2032","Board the sense\u2013decide\u2013act loop; test it against the disputed cards."),
   ("12\u2032","Form teams of 2\u20133; assign rotating roles: driver, navigator, documenter."),
   ("13\u2032","Inventory the mBot2 box against its printed parts chart; peel the CyberPi screen film. The Rover box stays sealed until Grade 8."),
   ("5\u2032","Journal setup + first entry: three robots you met this week without noticing.")],
 "tips":["Only the mBot2 box opens this year \u2014 the sealed Rover box is Grade 8\u2019s reveal; store it safely.",
   "Photograph the sorted kit; it becomes the reference when parts go missing."],
 "result":("cards", {}),
 "success":["Every student can state the three-part robot test",
   "Kit inventory checked and signed off","Teams formed, roles written in the journal"]},

{"n":2, "title":"Assembly I",
 "goal":"Chassis, motors and wheels assembled correctly, following the visual guide.",
 "teach":[
   "The mBot2 build guide is visual (almost no text) \u2014 that is deliberate: reading an exploded diagram is an engineering skill. Teach students to check each diagram for three things before touching a part: <b>which parts</b>, <b>which orientation</b>, <b>which screws</b>.",
   "The single most common error is mounting a motor backwards or swapping left/right motor cables. Institute a rule: before wheels go on, the teacher (or a checker team) verifies motor orientation against the guide."],
 "guide":[
   ("Steps","\u2460 \u2013 \u2462 (printed pp. 9\u201310)"),
   ("Screws","M4\u00d78 \u00d74 (motors) \u00b7 M2.5\u00d712 \u00d72 (wheels)"),
   ("Sequence","cables into motors FIRST \u00b7 hub pressed into tyre \u00b7 motors into chassis \u00b7 wheels on")],
 "steps":[
   ("5\u2032","Demo: how to read one exploded diagram (parts \u2192 orientation \u2192 screws). Use guide step \u2461 as the example."),
   ("30\u2032","Teams build guide steps \u2460\u2013\u2462: motor cables in, wheels pressed together, motors into chassis (M4\u00d78), wheels onto shafts (M2.5\u00d712). Screws finger-tight first, then snug."),
   ("5\u2032","Teacher checkpoint: motor orientation + cable routing before wheels go on."),
   ("5\u2032","Journal: one diagram that was confusing and how you decoded it.")],
 "tips":["Plug each motor cable in BEFORE the motor goes into the chassis \u2014 the port is hard to reach after (guide step \u2460 order).",
   "The four long M4\u00d725 screws are Session 3\u2019s (shield) \u2014 if a team reaches for them today, they\u2019re on the wrong step.",
   "Do not overtighten into plastic; snug is enough.",
   "Half-built is fine \u2014 the cart shelf keeps work-in-progress safe."],
 "result":("expl", {"variant":"drive"}),
 "success":["Chassis + motors mounted, orientation verified","No leftover \u201cmystery screws\u201d",
   "Work-in-progress stored safely on the team shelf"]},

{"n":3, "title":"Assembly II",
 "goal":"Robot fully assembled, cables managed, battery installed \u2014 and QC-checked by another team.",
 "teach":[
   "Finish the build: the mBot2 Shield (its battery is built in — charge it beforehand), CyberPi on top, sensor connections (ultrasonic front, line-follower under the nose). Cable management is not cosmetic \u2014 a loose cable in a wheel is the #1 cause of \u201cmy robot randomly stops\u201d.",
   "Introduce peer quality control: each team inspects another team\u2019s robot against a four-point checklist (wheels turn freely, cables tucked, battery secured, nothing rattles when gently shaken). Signing another team\u2019s checklist creates accountability and sharp eyes."],
 "guide":[
   ("Steps","\u2463 \u2013 \u2469 (printed pp. 11\u201314)"),
   ("Screws","M4\u00d714 \u00d72 (RGB + mini wheel) \u00b7 M4\u00d714 \u00d72 (ultrasonic) \u00b7 M4\u00d725 \u00d74 (shield)"),
   ("Cables","Quad RGB + ultrasonic each on a 10 cm mBuild cable \u2014 the guide red-crosses the 20 cm"),
   ("Motors","left \u2192 EM1, right \u2192 EM2 (guide step \u2467 wiring tips)")],
 "steps":[
   ("25\u2032","Finish guide steps \u2463\u2013\u2468: Quad RGB + mini wheel underneath (M4\u00d714), ultrasonic up front (M4\u00d714), shield on top (M4\u00d725 \u2014 the four long ones), motors to EM1/EM2, CyberPi slides in last; route and tuck everything."),
   ("10\u2032","Cross-team QC: inspect + sign another team\u2019s checklist; fix anything flagged."),
   ("5\u2032","Shake test + wheel spin test in front of the class."),
   ("5\u2032","Journal: what did QC catch on the robot you inspected?")],
 "tips":["The ultrasonic sensor must face exactly forward \u2014 a tilted sensor gives garbage readings for weeks.",
   "10 cm cable for the sensors \u2014 teams grabbing the 20 cm one are on the step the guide crosses out in red.",
   "EM1/EM2 swapped = robot turns when told to go straight; check before closing up.",
   "Label each robot with the team name now."],
 "result":("expl", {"variant":"sense"}),
 "success":["Robot passes all four QC points, signed by another team",
   "Sensors mounted straight and plugged into the correct ports","Team label on the robot"]},

{"n":4, "title":"First Boot",
 "goal":"Robot connects to mBlock, firmware updated, and greets the world on its screen.",
 "teach":[
   "Tour the CyberPi: full-color screen, joystick, buttons A/B, speaker, microphone, light sensor, LED strip. This little brick is the robot\u2019s brain and face \u2014 everything students program flows through it.",
   "Walk the connection ritual as a checklist students will repeat every session: power on \u2192 open mBlock \u2192 add device \u201cCyberPi\u201d \u2192 connect (USB first time, then Bluetooth) \u2192 update firmware if prompted. Then the classic first program: show a greeting on the screen. It is one block \u2014 and it proves the whole chain works: their code, running on their robot."],
 "steps":[
   ("8\u2032","CyberPi guided tour \u2014 students point to each part as it\u2019s named."),
   ("15\u2032","Connection ritual step by step; firmware update (this is the slow part)."),
   ("12\u2032","Program: on start \u2192 show \u201cHello, I am <robot name>!\u201d; add a beep and an LED color."),
   ("5\u2032","Each robot greets the class from the front desk."),
   ("5\u2032","Journal: write the connection ritual in your own words \u2014 it\u2019s next session\u2019s entry ticket.")],
 "code":("blocks",
"when flag clicked\n  show label \"Hello, I am ZAP!\" on screen\n  play sound  hello\n  set all LEDs to  blue"),
 "tips":["Firmware updates can take minutes \u2014 do a teacher dry run before this session.",
   "If Bluetooth pairing fails, USB always works; don\u2019t burn class time fighting it."],
 "result":("screen", {"lines":[("Hello, I am","#7dd3fc",11,False),("ZAP!","#facc15",16,True)],
   "caption":"every robot shows its greeting \u2014 code runs on hardware"}),
 "success":["Robot connects and receives programs","Greeting + sound + LED all fire on start",
   "Students can recite the connection ritual"]},

# ---------------- UNIT 2
{"n":5, "title":"First Motion & Calibration",
 "goal":"The robot drives exactly 50 cm \u2014 and students understand why \u201cexactly\u201d needs calibration.",
 "teach":[
   "First motion program: drive forward 50 cm, stop. Then measure with a ruler. Robots will land at 47, 52, 49 cm\u2026 Why? Wheel slip, battery level, floor surface. This gap between <b>commanded</b> and <b>actual</b> is one of the deepest ideas in robotics \u2014 and students discover it with a ruler.",
   "Introduce the calibration cycle: command \u2192 measure \u2192 compute error \u2192 adjust \u2192 repeat. Teams tune until three runs in a row land within \u00b11 cm of the 50 cm mark."],
 "steps":[
   ("5\u2032","Connection ritual (entry ticket) \u2014 all robots online."),
   ("10\u2032","Program + first run: forward 50 cm. Measure and record actual distance, three runs."),
   ("20\u2032","Calibration cycle: adjust and re-test until 3\u00d7 within \u00b11 cm; record the table in the journal."),
   ("10\u2032","Class data on the board: whose robot drifted most? Same floor, same code \u2014 discuss why.")],
 "code":("blocks",
"when button A pressed\n  move forward 50 cm at 50 RPM\n  stop moving\n  show label \"done\" on screen"),
 "tips":["Same start line for every run \u2014 tape it on the floor.",
   "Low battery changes distance; note battery level next to each measurement."],
 "result":("calibrate", {}),
 "success":["Three consecutive runs land within \u00b11 cm of the mark",
   "Calibration table recorded (commanded / actual / error)",
   "Students can explain one reason commanded \u2260 actual"]},

{"n":6, "title":"Shapes",
 "goal":"The robot drives a closed square and triangle using precise turns.",
 "teach":[
   "Driving a square = four times (forward, turn 90\u00b0). But which 90\u00b0? Have students walk a square themselves: at each corner they turn 90\u00b0 \u2014 the <b>exterior</b> angle. For a triangle the turn is 120\u00b0, not 60\u00b0. The rule they should discover: exterior angles of any closed shape sum to 360\u00b0, so each turn = 360\u00b0 \u00f7 number of sides.",
   "Chalk or tape the start point. A perfect shape ends exactly where it began \u2014 that\u2019s the built-in accuracy test, and it sets up next session\u2019s competition."],
 "steps":[
   ("5\u2032","Humans walk a square in the aisle; feel the exterior angle."),
   ("12\u2032","Program the square (no loops yet \u2014 write all 8 blocks; the pain is the point)."),
   ("13\u2032","Triangle: teams predict the turn angle before testing. 60\u00b0 fails beautifully."),
   ("10\u2032","Measure gap between start and end point for the best shape; record."),
   ("5\u2032","Journal: the 360\u00b0 rule in your own words + a drawing.")],
 "code":("blocks",
"when button A pressed\n  move forward 30 cm\n  turn right 90\u00b0\n  move forward 30 cm\n  turn right 90\u00b0\n  move forward 30 cm\n  turn right 90\u00b0\n  move forward 30 cm\n  turn right 90\u00b0   <- back at start?"),
 "tips":["Let teams try 60\u00b0 for the triangle and watch it spiral \u2014 the error teaches the rule.",
   "Turning accuracy varies with speed; slower turns are more precise."],
 "result":("path", {"shape":"square","caption":"a closed square \u2014 robot ends on its start point"}),
 "success":["Square closes within a few cm of the start point",
   "Triangle drawn with the correct 120\u00b0 exterior turn",
   "Team can state the 360\u00b0 \u00f7 sides rule"]},

{"n":7, "title":"Pentagram Challenge",
 "goal":"The robot draws a five-pointed star \u2014 and the team with the smallest start/end gap wins.",
 "teach":[
   "A pentagram is the payoff of the 360\u00b0 rule with a twist: the robot turns through 720\u00b0 total (it wraps around twice), so each of the 5 turns is <b>144\u00b0</b>. Don\u2019t give the answer \u2014 give the hint \u201cthe star wraps around twice\u201d and let teams derive it.",
   "This is also the first competition with rules: same side length for everyone (e.g. 40 cm), same floor, three official attempts, best one counts, gap measured with a ruler. Small, fair, measurable competitions are the engine of this whole program."],
 "steps":[
   ("10\u2032","Derive the turn angle in teams (hint: 720\u00b0 total). Verify: 720 \u00f7 5 = 144\u00b0."),
   ("20\u2032","Build and tune the star program; calibrate turns at low speed."),
   ("12\u2032","Official attempts: 3 runs, measure start/end gap, best counts."),
   ("3\u2032","Podium + journal: your gap, and one tuning change that improved it.")],
 "code":("blocks",
"when button A pressed\n  repeat 5\n    move forward 40 cm\n    turn right 144\u00b0\n  play sound  celebrate"),
 "tips":["Teams that discovered repeat-blocks early will use them here \u2014 let them, and showcase it as next session\u2019s topic.",
   "Fresh batteries for official attempts; it genuinely matters."],
 "result":("path", {"shape":"star","caption":"a five-pointed star, closed within centimeters"}),
 "success":["Star visibly closes (gap under ~5 cm)","Team derived 144\u00b0 rather than being told",
   "Three official attempts recorded with measured gaps"]},

# ---------------- UNIT 3
{"n":8, "title":"Loops",
 "goal":"Students refactor repeated code into loops and nest loops for patterns.",
 "teach":[
   "Show the 8-block square from Session 6 next to a 3-block loop version. Same behavior, less code, one place to change. That is the whole argument for loops \u2014 and students who hand-wrote the star\u2019s five sides feel it in their fingers.",
   "Then nest: a loop inside a loop. Example: repeat 4 [ blink LEDs red\u2013blue 3 times, then turn 90\u00b0 ]. Ask before each run: \u201chow many total blinks?\u201d Predicting the count (4 \u00d7 3 = 12) is the comprehension check."],
 "steps":[
   ("8\u2032","Refactor the square into a repeat-4 loop; verify identical behavior."),
   ("10\u2032","LED patterns with loops: police strobe, rainbow cycle, heartbeat."),
   ("17\u2032","Nested loop challenge: square where each corner blinks 3\u00d7. Predict total blinks first."),
   ("10\u2032","Mini-exercises: change one number to make the shape a hexagon. Which number(s)?")],
 "code":("blocks",
"when button A pressed\n  repeat 4              <- outer loop\n    repeat 3            <- inner loop\n      set all LEDs to red\n      wait 0.2 s\n      set all LEDs to blue\n      wait 0.2 s\n    move forward 30 cm\n    turn right 90\u00b0"),
 "tips":["\u201cHow many times does the inner block run in total?\u201d \u2014 ask it every single time.",
   "Hexagon answer: repeat 6 + turn 60\u00b0 \u2014 two numbers change, and both come from the 360\u00b0 rule."],
 "result":("path", {"shape":"square","caption":"the same square \u2014 now 3 blocks instead of 8, corners blinking"}),
 "success":["Square rebuilt with a loop, behavior identical",
   "Nested-loop blink count predicted correctly before running",
   "Team converted the square to a hexagon by changing two numbers"]},

{"n":9, "title":"Robot Dance",
 "goal":"A 30-second choreography syncing motion, LEDs and sound \u2014 performed for the class.",
 "teach":[
   "Creative constraint session: exactly 30 seconds, must use at least one loop, one nested pattern, motion + light + sound together. Constraints force design decisions \u2014 that\u2019s the lesson hiding inside the fun.",
   "Timing is the technical skill here: blocks run one after another, so students must budget their 30 seconds (spins take ~1 s per 180\u00b0 at medium speed, sounds have lengths). Storyboard first on paper: a timeline strip with what happens at 0 s, 5 s, 10 s\u2026"],
 "steps":[
   ("5\u2032","Brief + judging categories: most precise, most creative, best sync."),
   ("8\u2032","Paper storyboard: the 30-second timeline."),
   ("22\u2032","Build and rehearse; iterate on timing."),
   ("10\u2032","Showcase: every team performs; class votes by category.")],
 "tips":["Cap volume \u2014 agree a max level before chaos begins.",
   "Clear a performance zone; spinning robots and table edges are enemies."],
 "result":("dance", {}),
 "success":["Performance lasts 28\u201332 seconds","At least one loop and one nested pattern in the code",
   "Motion, LEDs and sound clearly synchronized at least once"]},

# ---------------- UNIT 4
{"n":10, "title":"Echolocation",
 "goal":"Students explain how ultrasonic sensing works and read live distances on screen.",
 "teach":[
   "The ultrasonic sensor shouts (at a pitch we can\u2019t hear) and times the echo. Distance = time \u00d7 speed of sound \u00f7 2 \u2014 the \u00f72 because sound travels there <i>and</i> back. Bats hunt with it; cars park with it. Have two students act it out: one claps, the other echoes after a delay proportional to distance.",
   "First sensing program: show the distance on the screen forever (a loop!). Then explore: what does it read for a book at 20 cm? A soft sweater? A hand at an angle? Soft and angled surfaces scatter the echo \u2014 real sensors have real limits, and students should catalogue them."],
 "steps":[
   ("8\u2032","Echolocation demo + the there-and-back \u00f72 idea."),
   ("12\u2032","Program: forever \u2192 show ultrasonic distance on screen. Ruler-check its accuracy."),
   ("15\u2032","Sensor limits lab: hard vs. soft targets, straight vs. angled; record readings."),
   ("10\u2032","Share the weirdest reading + explain it with the echo model.")],
 "code":("blocks",
"when flag clicked\n  forever\n    show label (ultrasonic distance) on screen\n    wait 0.1 s"),
 "tips":["Below ~4 cm and beyond ~3 m readings go strange \u2014 let students find these edges themselves.",
   "The sensor sees a cone, not a laser line \u2014 nearby objects off-axis still reflect."],
 "result":("sonar", {"dist":"24 cm"}),
 "success":["Live distance updates on screen and matches a ruler within ~1 cm",
   "Team recorded at least two \u201cweird\u201d readings and explained them",
   "Students can explain the \u00f72 in the distance formula"]},

{"n":11, "title":"Conditionals",
 "goal":"The robot stops by itself exactly 5 cm from a wall, from any starting distance.",
 "teach":[
   "Enter <b>if</b>: for the first time, the robot makes a decision. \u201cIf distance < 10 cm \u2192 stop\u201d inside a forever loop is the sense\u2013decide\u2013act loop made real \u2014 point back to the Session 1 poster; this is that diagram, running.",
   "Then the precision challenge: stop at exactly 5 cm. Naive code overshoots \u2014 the robot is fast and checks the sensor only every loop pass. Students discover the fix themselves: approach slower, or slow down as the wall gets close (two thresholds: far \u2192 fast, near \u2192 slow, at 5 \u2192 stop). That layered answer previews proportional control in Grade 9."],
 "steps":[
   ("8\u2032","Build stop-if-close v1; watch it overshoot at full speed."),
   ("20\u2032","Iterate: slower approach, then two-speed approach. Measure the stopping gap each attempt."),
   ("12\u2032","Official challenge: 3 runs from different starting distances; average gap recorded."),
   ("5\u2032","Journal: why does speed change the stopping distance?")],
 "code":("blocks",
"when button A pressed\n  forever\n    if ultrasonic distance > 20\n      move forward at 50 RPM\n    else if ultrasonic distance > 5\n      move forward at 15 RPM   <- creep\n    else\n      stop moving\n      play sound  beep"),
 "tips":["A robot that never stops usually has the if outside the forever loop \u2014 the #1 bug today.",
   "Tell teams the two-speed trick exists only if they\u2019re stuck after 10 minutes."],
 "result":("sonar", {"dist":"5 cm","stop":True}),
 "success":["Robot stops without human help from any starting distance",
   "Average stopping gap within ~1 cm of the 5 cm target",
   "Code uses if/else inside a forever loop"]},

{"n":12, "title":"Wander Mode",
 "goal":"The robot roams the arena indefinitely, avoiding every obstacle on its own.",
 "teach":[
   "Combine everything: drive until something is close, then back up, turn, continue \u2014 forever. This is a real autonomous behavior, the same core logic as a robot vacuum.",
   "Add randomness: instead of always turning 90\u00b0, turn a random angle between 60\u00b0 and 120\u00b0. Ask why that helps \u2014 a fixed angle can trap the robot bouncing in a corner forever; randomness breaks the pattern. (This is a genuinely deep idea: randomness as an escape from loops.)"],
 "steps":[
   ("10\u2032","Build wander v1 with a fixed 90\u00b0 turn; test in the arena."),
   ("10\u2032","Find the corner trap (or stage one); introduce the random block."),
   ("15\u2032","Tune: detection threshold, backup distance, random range. Longest run wins."),
   ("10\u2032","Arena timing: longest continuous run without touching a wall.")],
 "code":("blocks",
"when button A pressed\n  forever\n    if ultrasonic distance < 12\n      move backward 10 cm\n      turn right (random 60 to 120)\u00b0\n    else\n      move forward at 40 RPM"),
 "tips":["Threshold too small \u2192 robot kisses walls; too big \u2192 robot is scared of everything. Tuning IS the lesson.",
   "Dark, soft obstacles reflect badly \u2014 use boxes, not backpacks."],
 "result":("wander", {}),
 "success":["Robot runs 60+ seconds in the arena with no wall contact",
   "Random turn range used and justified","Team tuned at least two parameters and logged the effect"]},

{"n":13, "title":"Arena + Debug Clinic \u2731",
 "goal":"Teams push wander mode to a personal best and practice structured debugging.",
 "teach":[
   "Today formalizes debugging as a four-step discipline: <b>predict</b> what the code should do \u2192 <b>test</b> \u2192 <b>observe</b> exactly what happened (not \u201cit\u2019s broken\u201d, but \u201cit turns left when the wall is on the left\u201d) \u2192 <b>fix one thing</b> and re-test. One change at a time \u2014 change three things and you learn nothing.",
   "Every team must produce one written bug report today: symptom, hypothesis, fix, result. Debugging is the most transferable skill in this whole course; treat the bug report as a first-class deliverable, not paperwork."],
 "steps":[
   ("5\u2032","Model one live debug on a teacher robot using the four steps aloud."),
   ("25\u2032","Teams improve their wander bots; every change logged as predict/test/observe/fix."),
   ("10\u2032","Official arena runs \u2014 beat your Session 12 time."),
   ("5\u2032","Teams read their best bug report aloud; class picks the \u201cbug of the day\u201d.")],
 "tips":["Buffer session: if the schedule slipped, this is the hour that absorbs it.",
   "Ban the sentence \u201cit doesn\u2019t work\u201d \u2014 require a symptom sentence instead."],
 "result":("journal", {"caption":"a real bug report \u2014 the deliverable of the day",
   "items":["symptom: turns INTO the wall","hypothesis: motors swapped","fix: swap M1/M2 cables","result: turns away \u2713","new best: 94 s no-touch"]}),
 "success":["New personal best arena time recorded",
   "At least one complete four-step bug report in the journal",
   "No change was made without a prediction first"]},

# ---------------- UNIT 5
{"n":14, "title":"Line Following I",
 "goal":"The robot follows the printed line using simple left/right correction.",
 "teach":[
   "The quad-RGB sensor under the nose reads how dark the floor is at four points. On the included map: white floor, black line. The simplest follower (\u201cbang-bang\u201d): if the line drifts left under the sensor \u2192 steer left; if right \u2192 steer right. Two rules, and the robot follows a curve. Magic \u2014 briefly.",
   "First: the calibration ritual. Every floor and lighting is different, so the sensor must learn \u201cwhite here\u201d vs. \u201cblack here\u201d (hold the calibrate button, sweep across the line). Make it a ritual like the connection checklist \u2014 uncalibrated sensors cause 80% of line-following tears.",
   "Let students watch closely: the robot zig-zags. Name it \u2014 <b>the wobble</b> \u2014 and write it on the board as an open question. It gets answered in Grade 9, and planting it now is the point."],
 "steps":[
   ("8\u2032","Sensor calibration ritual on the map \u2014 every team, every robot."),
   ("15\u2032","Build bang-bang follower; first laps on the oval."),
   ("12\u2032","Observe and sketch the wobble in the journal; slow-motion phone video helps."),
   ("10\u2032","Wobble question on the board: why does it zig-zag? Collect hypotheses \u2014 don\u2019t answer.")],
 "code":("blocks",
"when button A pressed\n  forever\n    if line sensor detects line on LEFT side\n      turn left slightly (L 20 / R 50 RPM)\n    else if line detected on RIGHT side\n      turn right slightly (L 50 / R 20 RPM)\n    else\n      move forward at 45 RPM"),
 "tips":["Re-calibrate whenever the robot moves to a different floor or the sun moves \u2014 seriously.",
   "Map curls at the edges cause false readings; tape it flat."],
 "result":("line", {"wobble":True}),
 "success":["Robot completes a full lap of the oval unassisted",
   "Calibration ritual performed from memory","Wobble observed, sketched, and hypothesized about"]},

{"n":15, "title":"Line Following II",
 "goal":"A smoother, faster follower using three states \u2014 and tuned speed values.",
 "teach":[
   "Upgrade from two rules to three states: line under the LEFT sensors \u2192 steer left; CENTER \u2192 drive straight; RIGHT \u2192 steer right. The new \u201cstraight\u201d state is what reduces the wobble: the robot stops over-correcting when it\u2019s already fine.",
   "Then tuning: base speed vs. correction strength. Fast base speed + weak correction = flies off curves. Slow + strong = crawls but never loses the line. Teams find their own sweet spot through timed laps \u2014 there is no single right answer, only trade-offs. Write \u201ctrade-off\u201d on the board; it\u2019s the engineering word of the day."],
 "steps":[
   ("10\u2032","Add the center/straight state; verify reduced wobble."),
   ("20\u2032","Tuning sprints: change ONE value, run a timed lap, log it. Repeat."),
   ("10\u2032","Best-lap trials: three official timed laps, best counts."),
   ("5\u2032","Journal: your final values + the trade-off you chose.")],
 "code":("blocks",
"forever\n  if line under CENTER sensors\n    move forward at 55 RPM        <- straight state\n  else if line under LEFT\n    set motors  L 15 / R 55 RPM\n  else if line under RIGHT\n    set motors  L 55 / R 15 RPM"),
 "tips":["One value per change \u2014 the debug discipline from Session 13 applies to tuning too.",
   "Losing the line at the same curve every lap = that curve is tighter than your correction strength."],
 "result":("line", {"wobble":False,"states":True,"caption":"three states, visibly smoother trajectory"}),
 "success":["Lap time improved vs. Session 14","Robot recovers the line on the tightest curve of the map",
   "Tuning log shows one-change-at-a-time discipline"]},

{"n":16, "title":"Events \u2731",
 "goal":"The robot starts on a button press and reacts to color patches on the track.",
 "teach":[
   "Events flip the program\u2019s shape: instead of one long script, code now waits for things to happen \u2014 a button press, a color under the sensor. \u201cWhen button B pressed \u2192 start following\u201d turns the robot into something you operate, not just launch.",
   "The quad-RGB sensor also reads <b>color</b>, not just dark/light. Add traffic rules to the track: a red patch = stop 2 s, a green patch = beep and continue. Students place the patches themselves \u2014 designing the track is half the fun and all of the ownership. This session is the direct rehearsal for the capstone\u2019s rescue-zone stop."],
 "steps":[
   ("8\u2032","Restructure: line following starts on button B, stops on button A."),
   ("18\u2032","Add color rules: red patch \u2192 pause 2 s; green \u2192 beep + continue. Place patches on the track."),
   ("14\u2032","Best-lap trials on the enriched track \u2014 rules must be obeyed to count."),
   ("5\u2032","Journal: list every event your program now responds to.")],
 "code":("blocks",
"when button B pressed\n  set  running  to 1\n\nwhen button A pressed\n  set  running  to 0\n  stop moving\n\nforever\n  if running = 1\n    ...line following...\n    if color sensor sees RED\n      stop moving, wait 2 s\n    if color sensor sees GREEN\n      play sound  beep"),
 "tips":["Buffer session \u2014 compress here if behind; the color rules can shrink to red-only.",
   "Glossy tape reflects oddly; matte paper patches read more reliably."],
 "result":("events", {}),
 "success":["Robot starts/stops on buttons only \u2014 no re-flashing between runs",
   "Both color rules obeyed on a full lap","Team designed and placed its own patch layout"]},

# ---------------- UNIT 6
{"n":17, "title":"Capstone: Plan",
 "goal":"A signed-off paper plan: flowchart of the full Rescue Run mission.",
 "teach":[
   "Reveal the mission: follow the line through the course, handle a surprise obstacle ON the line, stop precisely inside the rescue zone (a colored patch), celebrate with lights + sound. Everything needed has been built in Sessions 10\u201316 \u2014 today is about <b>assembling</b> known pieces, which is what real engineering mostly is.",
   "No code today. Teams produce a flowchart: boxes for states (following / avoiding / stopped / celebrating), arrows for the events that switch between them. The teacher sign-off gate is strict: a plan that can\u2019t answer \u201cwhat does the robot do when X?\u201d goes back for revision. Planning discipline now saves two sessions of chaos later."],
 "steps":[
   ("8\u2032","Mission briefing + rubric walkthrough (autonomy, precision, code quality, presentation)."),
   ("10\u2032","Decompose in teams: list the sub-behaviors and which past session built each."),
   ("20\u2032","Draw the flowchart; walk it with a finger while a teammate plays \u201crobot\u201d."),
   ("7\u2032","Sign-off interviews: teacher asks two \u201cwhat if\u2026\u201d questions per team.")],
 "tips":["Refuse vague boxes like \u201cdo the thing\u201d \u2014 every box must be a behavior they have already built.",
   "The obstacle sits ON the line: teams must realize avoidance means leaving and re-finding the line."],
 "result":("journal", {"caption":"a signed flowchart \u2014 the ticket to touch the keyboard",
   "items":["[follow line] --obstacle<12cm-->","[back up + arc around]","[re-find line] --> follow","[see RED zone] --> stop","[celebrate!]  \u2713 signed: Ms. K"]}),
 "success":["Flowchart covers all four mission phases",
   "Team answered both \u201cwhat if\u201d questions without hand-waving","Teacher signature on the plan"]},

{"n":18, "title":"Capstone: Build I",
 "goal":"Line following + precise rescue-zone stop working end-to-end.",
 "teach":[
   "Build in the order of the flowchart, and integrate one piece at a time: first, clean line following on the capstone course; then the red-zone stop. Resist teams that want to build everything at once \u2014 \u201cmake one arrow of the flowchart work, then the next\u201d is the mantra.",
   "The zone stop reuses Session 16\u2019s color event, but precision matters now: the robot must halt <i>inside</i> the zone. If it slides past, lower approach speed near the zone \u2014 the Session 11 two-speed idea returns, and students should recognize it."],
 "steps":[
   ("5\u2032","Flowchart on the table; agree today\u2019s target: phases 1 + 4 (follow, stop, celebrate)."),
   ("30\u2032","Build + test line \u2192 zone stop \u2192 celebration on the real course."),
   ("10\u2032","Milestone demo to the teacher: three clean follow-and-stop runs.")],
 "tips":["Keep the obstacle OFF the course today \u2014 one variable at a time.",
   "Celebration code is morale fuel; let them make it loud (within the volume pact)."],
 "result":("line", {"wobble":False,"caption":"follow \u2192 stop inside the zone \u2192 celebrate, three times in a row"}),
 "success":["Three consecutive runs: full lap + stop inside the zone",
   "Celebration triggers only in the zone, not on other colors","Code matches the flowchart phases 1 and 4"]},

{"n":19, "title":"Capstone: Build II \u2731",
 "goal":"The full mission runs: obstacle handled, line re-found, zone stop preserved.",
 "teach":[
   "Integrate the hard part: the obstacle sits on the line, so the robot must notice it (ultrasonic, Session 11), leave the line, arc around (motion, Sessions 5\u20137), and re-acquire the line (a search behavior \u2014 the one genuinely new piece). Simplest re-find: after the arc, drive forward slowly until any line sensor fires, then resume following.",
   "Then rehearse under competition conditions: full runs, timed, from the official start. Teams should also decide their run-day parameters (speeds, thresholds) and freeze them \u2014 tinkering minutes before an official run is how good robots die."],
 "steps":[
   ("25\u2032","Build the avoid-and-refind behavior; test with the obstacle at different points on the line."),
   ("13\u2032","Full dress rehearsals from the official start line; log completion of each phase."),
   ("7\u2032","Freeze parameters; write them in the journal as the \u201crace configuration\u201d.")],
 "tips":["Buffer session \u2014 a struggling class can make the obstacle position fixed and known.",
   "The arc must be wide enough to clear the obstacle but tight enough to land near the line \u2014 pure tuning."],
 "result":("rescue", {}),
 "success":["At least one full clean run: follow \u2192 avoid \u2192 re-find \u2192 zone stop \u2192 celebrate",
   "Re-find works with the obstacle at two different positions","Race configuration frozen and written down"]},

{"n":20, "title":"Scored Runs & Reflection",
 "goal":"Two official scored attempts, a short team presentation, and an honest retrospective.",
 "teach":[
   "Run it like an event: official start line, a visible scoreboard (phases completed \u00d7 points, small time bonus), two attempts per team, best counts. Between attempts teams may fix code \u2014 under time pressure, exactly like a real robotics competition pit.",
   "The presentation matters as much as the run: 2 minutes per team \u2014 what worked, what failed, what you\u2019d do next. Normalize talking about failure; the team whose robot crashed but who can explain <i>why</i> deserves loud applause. Close by seeding next year: \u201cyour robot gets a face and tracks.\u201d"],
 "steps":[
   ("8\u2032","Setup, scoreboard, attempt order drawn by lot."),
   ("22\u2032","Official attempts (2 per team) with pit time between rounds."),
   ("10\u2032","Team presentations: worked / failed / next \u2014 2 minutes each."),
   ("5\u2032","Individual reflection in the journal + Grade 8 teaser.")],
 "tips":["Score phases, not just full success \u2014 a robot that avoids but misses the zone still earns points.",
   "Photograph the scoreboard; it opens Grade 8, Session 1\u2019s review quiz."],
 "result":("rescue", {}),
 "success":["Every team completed two official attempts","Scores recorded phase by phase on the public board",
   "Every student wrote a personal what-I\u2019d-do-next reflection"]},
]


# --- Revision: exact pieces per the official mBot2 box packing list (photo-verified)
PARTS = {
 1:[("kitbox","full inventory vs. the box\u2019s parts chart"),("cards","robot-or-not deck"),("journal","1 per student"),("trays","sort screws by size now")],
 2:[("chassis",None),("motor","check orientation!"),("wheelset","\u00d72 each: hub + tyre"),("motorcable","\u00d72 \u2014 plug in first"),("screws7","M4\u00d78 \u00d74 + M2.5\u00d712 \u00d72"),("screwdriver","in the box")],
 3:[("cyberpi","the brain"),("shield","battery is built in \u2014 charged?"),("ultra","front, facing exactly forward"),("quadrgb","under the nose"),("miniwheel","mounts with the RGB sensor"),("mbuild","10 cm \u00d72 \u2014 NOT the 20 cm"),("screws7s","M4\u00d714 \u00d74 + M4\u00d725 \u00d74"),("screwdriver",None)],
 4:[("robot_wheel","fully built + QC\u2019d"),("laptop","mBlock installed"),("usb","first pairing is wired"),("dongle","advised by Makeblock \u2014 sold separately")],
 5:[("robot_wheel",None),("laptop",None),("ruler","or tape measure"),("tape","start line on floor"),("journal","calibration table")],
 6:[("robot_wheel","calibrated"),("laptop",None),("tape","mark the start point"),("ruler","measure the gap")],
 7:[("robot_wheel",None),("laptop",None),("tape","official start point"),("ruler","gap measurement"),("shield","charged for official runs")],
 8:[("robot_wheel",None),("laptop",None),("journal","blink-count predictions")],
 9:[("robot_wheel",None),("laptop",None),("timer","30-second limit"),("tape","performance zone")],
 10:[("robot_wheel",None),("laptop",None),("ruler","verify readings"),("boxes","hard + soft targets")],
 11:[("robot_wheel",None),("laptop",None),("boxes","the wall"),("ruler","stopping-gap check")],
 12:[("robot_wheel",None),("laptop",None),("boxes","arena walls + obstacles"),("timer","longest-run timing")],
 13:[("robot_wheel",None),("laptop",None),("boxes","arena"),("timer",None),("journal","bug report \u2014 graded")],
 14:[("robot_wheel",None),("laptop",None),("map","in the mBot2 box"),("tape","tape it flat!"),("phone","slow-mo the wobble")],
 15:[("robot_wheel",None),("laptop",None),("map","calibrated on THIS floor"),("timer","lap times"),("journal","tuning log")],
 16:[("robot_wheel",None),("laptop",None),("map",None),("patches","matte paper, red + green"),("timer",None)],
 17:[("journal","flowchart \u2014 today\u2019s deliverable"),("cards","rubric handout"),("map","course planning reference"),("robot_wheel","reference only \u2014 no coding today")],
 18:[("robot_wheel",None),("laptop",None),("map","capstone course"),("patches","rescue zone"),("tape","course layout")],
 19:[("robot_wheel",None),("laptop",None),("map",None),("patches",None),("boxes","the obstacle, ON the line"),("shield","note battery level in journal")],
 20:[("robot_wheel","race configuration frozen"),("laptop",None),("map",None),("patches",None),("boxes",None),("timer","+ visible scoreboard"),("shield","charged \u2014 official runs")],
}
